### ISSUE TITLE
Content > Startseite > Sponsoren einbinden

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#10]
Auf der Startseite mit grauem Balken (entgegen Entwurf) Sponsor Mittwald einbinden.

**Comment by SniperSister** [comment]
Wo genau soll das hin? Haste da ein kleines Mockup für mich?

**Comment by coolcat-creations** [comment]
So wie auf https://basecamp.com/2809782/projects/7777654/messages/42488018 nur in grau und ohne Unterzeile.

**Comment by SniperSister** [comment]
Erledigt!
