### ISSUE TITLE
Content > News > Datum

### ISSUE THREAD

**Issue by SniperSister** [JandBeyond/joomlade#100]
In der Detailansicht der Newsbeiträge fehlt das Datum:
http://forum.joomla.de/index.php/Thread/1071-Datum-in-Beitr%C3%A4gen-auf-Joomla-de/?postID=7042#post7042

**Comment by drmenzelit** [comment]
Menüitem Aktuelles geändert um Erstellungsdatum anzuzeigen.

**Comment by SniperSister** [comment]
Habe jetzt noch das doppelte Datum im Kategorieblog rausgenommen :)
