### ISSUE TITLE
E-Learning Video Anbindung 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#102]
Wir haben ja in Essen darüber gesprochen das wir auch zukünftig einbinden wollen. Hierfür müsste auf der Webseite eine Grundlage geschaffen werden.

**Comment by ufuk-avcu** [comment]
Hierzu würde ich einen Untermenüpunkt bei dem Menüpunkt "Wissen" anlegen. Diesen könnte man "Video Tutorials" nennen. Vorerst würde ich es als Kategorie-Blog anlegen, damit es nicht allzu kompliziert wird.

**Comment by widmann-it** [comment]
das ist schon alles fertig eingerichtet �� 

Original Message processed by david®  
Re: [JandBeyond/joomlade] E-Learning Video Anbindung (#102) (15-Jun-2016 12:30)
From:   Ufuk Avcu
To:JandBeyond/joomlade
Cc (2):Assign, widmann-it

Hierzu würde ich einen Untermenüpunkt bei dem Menüpunkt "Wissen" anlegen. Diesen könnte man "Video Tutorials" nennen. Vorerst würde ich es als Kategorie-Blog anlegen, damit es nicht allzu kompliziert wird.

**Comment by widmann-it** [comment]
Hey Niels, 
wie weit bist du mit der Anbindung ? Muss noch was gemacht werden und brauchst du Hilfe?

**Comment by widmann-it** [comment]
Erledigt
