### ISSUE TITLE
Kalendereinträge der JUGS

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#103]
Hier sollten wir uns eine andere Lösung überlegen. Immer wieder bekomme ich Termine von den verschiedenen JUG und habe jedesmal das Problem das die Einträge der JUGs nicht auftauchen.

**Comment by SniperSister** [comment]
Was meinst du mit "nicht auftauchen"? Hast du auf dem schirm, dass die Einträge für 1 Stunde gecached werden und Änderungen erst dann sichtbar sind?

**Comment by widmann-it** [comment]
Sorry "Auftauchen" ist dem zusammenhang falsch ausgedrückt, es geht darum das der Weg die aktuellen Termine der JUGs einzutragen zu umständlich ist. Ich vermisse z.B. die Termine von Koblenz & Fulda fehlen. Von den Verantwortlichen bekomme ich die Rückmeldung das hierfür keinen Anlaufpunkt gibt.

**Comment by SniperSister** [comment]
Die Termine von Koblenz sind drin, siehe Kalender rechte Seite:
https://www.joomla.de/events/jugs

Und Christine hat ebenfalls Zugriff auf den Google Kalender und könnte ihre Termine pflegen.

**Comment by widmann-it** [comment]
Ja auf der Gesamtseite ;-) Das Problem ist eher das in der Vorschau der Kalenderansicht der Termin 
erst am Tag der Veranstaltung angezeigt wird. Dies kommt daher das entweder am gleichen Tag oder davor einige Termine sind. Ok, gerade hab ich gesehen das es im April nicht so ist.
