### ISSUE TITLE
forum. und stats. auf https:// umstellen

### ISSUE THREAD

**Issue by SniperSister** [JandBeyond/joomlade#108]
Wir wollen die beiden Seiten ebenfalls auf https:// umstellen

**Comment by tecpromotion** [comment]
Zertifikate sind beantragt. Denke das ist Montag dann abgeschlossen und wir können umstellen.

**Comment by tecpromotion** [comment]
@SniperSister 
So fertig. Ging doch am Wochenende.

https://stats.joomla.de/ funktioniert
https://forum.joomla.de/ funktioniert. Bitte noch die Ressourcen die per http:// geladen werden durch https:// abändern.

**Comment by SniperSister** [comment]
Erledigt, forum.joomla.de hat auch schon per htaccess den Redirect auf https
