### ISSUE TITLE
Joomla.de von GA auf Piwik umstellen

### ISSUE THREAD

**Issue by SniperSister** [JandBeyond/joomlade#109]
Sobald #108 erledigt ist kann Joomla.de auch auf Piwik umgestellt werden

**Comment by togethere** [comment]
Okay, ich fand es schon merkwürdig und als Patrick jetzt auch erstaunt war (öhöm!) wollte ich mal fragen warum?

**Comment by SniperSister** [comment]
Datenschutz :) Warum der allwissenden Datenkracke mehr Infos in den Rachen werfen als nötig ;)

**Comment by togethere** [comment]
Joa, kann man machen.... Frag mal den Markus nach seinem Lieblings T-Shirt

**Comment by SniperSister** [comment]
Tz tz tz, das ist aber ein wenig konstruktiver Beitrag ;)

Mal im Ernst: gibt es sachliche Gründe die zwingend für GA sprechen? Ich lasse mich gerne überzeugen.

**Comment by togethere** [comment]
Prinzipiell ist es ja so, dass die Datenkrake nicht nur nimmt, sie gibt uns ja auch was zurück und in Verbindung mit der SearchConsole hat man wunderbare Möglichkeiten die Suchen der Menschen zu analysieren und dann heraus zu lesen, was Ihr Begehr ist. Daher wissen wir im Moment auch, dass das Thema Sicherheit ein ganz großes für Joomla! ist, das wir unbedingt dringend beackern sollten. 

Also prinzipiell ist es ein Geben und Nehmen. Sicher ist es immer noch Google. Stimmt! Aber sind wir nicht auch alle auf Facebook? Man muss also abwägen, wo der Vorteil ist.

**Comment by SniperSister** [comment]
Ich weiß dass GA zusammen mit der Console bessere Auswertungsmöglichkeiten hat, kann aber nicht abschätzen, ob die Vorteile es rechtfertigen, die Einbindung drin zu lassen.

Wie knobeln wir das also aus?
