### ISSUE TITLE
Dev > Startseite > Faktenkasten einbinden

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#11]
Faktenkasten mit Zahlen (siehe Entwurf) mit Verbindung zu Facebook etc. einbinden.

**Comment by zero-24** [comment]
hmm welcher Entwurf?

War so etwas gemeint?
![image](https://cloud.githubusercontent.com/assets/2596554/18798595/8e67efe6-81d3-11e6-8544-78376c92641f.png)

**Comment by dneukirchen** [comment]
Ich glaub damit ist eher sowas gemeint, oder?
- 65 +MILLION INSTALLATIONS
- 13 + THOUSAND EXTENSIONS & TEMPLATES
- 3 +MILLION FORUM POSTS
- 1+ THOUSAND VOLUNTEERS 
- 550 + THOUSAND LINES OF CODE
- 64LANGUAGES

@coolcat-creations ist der entwurf irgendwo online?

**Comment by widmann-it** [comment]
Wer kann es Einbinden :-) Ich denke es ging auch um die Fakten wiw David SIe Beschrieben hat.

**Comment by zero-24** [comment]
Wo sollen die denn eingebunden werden?

**Comment by widmann-it** [comment]
wie david oben geschrieben hat :-) Nur mit den Aktuellen Daten

**Comment by zero-24** [comment]
Wo nicht was 😜

**Comment by tecpromotion** [comment]
closed
