### ISSUE TITLE
SEO Alt Tags für Bilder setzen

### ISSUE THREAD

**Issue by togethere** [JandBeyond/joomlade#116]
https://www.joomla.de/images/aktuelles/joomla_releases_348_blogpost-01.jpg
https://www.joomla.de/images/Beitragsbilder/joomla35graphic_small.png
https://www.joomla.de/images/aktuelles/joomla_oh_deer.jpg
https://www.joomla.de/images/aktuelles/security.png
https://www.joomla.de/images/Beitragsbilder/magazin-thumb.jpg
https://www.joomla.de/images/aktuelles/wb.jpg
https://www.joomla.de/images/thumbs/structure_thumb.png
https://www.joomla.de/images/aktuelles/small/jd_blindbird_min.png
https://www.joomla.de/images/Beitragsbilder/joomla35graphic.png
https://www.joomla.de/images/thumbs/joomla34graphic_small.png
https://www.joomla.de/images/Beitragsbilder/joomla34graphic.png
https://www.joomla.de/images/aktuelles/jd_blindbird.png
https://www.joomla.de/images/Beitragsbilder/joomlacamp.png
https://www.joomla.de/images/aktuelles/pbf2.jpg
https://www.joomla.de/images/aktuelles/aktuelles.jpg
https://www.joomla.de/images/Beitragsbilder/Hackathon/IMG_20160315_195920.JPG
https://www.joomla.de/images/aktuelles/small/pbf2_thumb.jpg

**Comment by widmann-it** [comment]
https://www.joomla.de/images/Beitragsbilder/Hackathon/IMG_20160315_195920.JPG erl.

**Comment by widmann-it** [comment]
https://www.joomla.de/images/Beitragsbilder/joomlacamp.png erl.

**Comment by widmann-it** [comment]
Komplett durchgegangen und entsprechend Angepasst
