### ISSUE TITLE
Kalender geht nicht mehr 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#117]
Unter https://www.joomla.de/events/jugs fehlt der Kalender

**Comment by SniperSister** [comment]
Ich denke das ist in dem Fall geplant, weil auf den Unterseiten jeweils nur das Eventformat beschrieben wird und der Kalender unter /events ist.

**Comment by widmann-it** [comment]
Nein da war ein Kalenderblatt mit allen Veranstaltungen, das Modul ist auch vorhanden es erfolgt jedoch keine Ausgabe.

**Comment by widmann-it** [comment]
jetzt ja ;-)
