### ISSUE TITLE
Links mit 404 Antwort

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#119]
Hier: https://www.joomla.de/joomla
Reiter: WIE ZUKUNFTSSICHER IST JOOMLA!? --> `(inter)nationale Unternehmen`
--> 404:  http://community.joomla.org/labels/joomla-portfolio.html
--> Neu: http://community.joomla.org/showcase/

Hier: https://www.joomla.de/community/jugs
Jug Aargau
--> 404: http://www.joomlastuff.ch/jug-im-aargau
--> Neu: http://www.joomlastuff.ch/jug-aargau

Hier: https://www.joomla.de/news/30-events/69-joomladay-2016-blindbird-ticket-sichern
-> 404: http://www.joomladay.de/fakten/jd16de-bb-banners-zum-herunterladen
-> Neu: http://www.joomladay.de/fakten/jd16de-regular-banners-zum-herunterladen

_ggf bei letzterem eine Weiterleitung auf joomladay.de seite?_

**Comment by dneukirchen** [comment]
und danke ;) Hast du n tool drüber laufen lassen oder manuell gesucht?

**Comment by zero-24** [comment]
Ein Tool: http://www.brokenlinkcheck.com/ :smile:

**Comment by dneukirchen** [comment]
:+1:
