### ISSUE TITLE
Joomla Usergroups Übersicht 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#120]
Hier sollte die Landkarte überarbeitet werden, die Punkte gehen sehr langsam auf.

**Comment by SniperSister** [comment]
Würde aktuell dazu tendieren das einfach durch ne 0815 Google Map zu ersetzen - Meinungen dazu?

**Comment by dneukirchen** [comment]
Glaube fast, dass es schneller wäre die blöden geocoder requests des weblink overrides einfach lange zu cachen oder in einem request zu vereinen... Irgendwer hat das ja damals mit nem weblink override umgesetzt. Problem liegt ja nur in den geocoding requests, die für jede jug bei jedem request abgefeuert werden.

So wären wir weiter synchron mit dem weblink modul rechts daneben (und vllt. auch an anderen stellen auf der website).

**Comment by dneukirchen** [comment]
Alternativ irgendein feld in der weblink komponente für lat und long missbrauchen... Dann sparen wir uns den ganzen blödsinn.

**Comment by SniperSister** [comment]
Problem ist dass das Modul aktuell die Geomap Visualization API verwendet und nicht die Maps API, da ist lat/lon übergeben so afaik nicht vorgesehen - daher mein Ansatz, dass auf ne gescheite Map mit der passenden API umzubauen

**Comment by dneukirchen** [comment]
dann machen wir das. Auf https://developers.google.com/chart/interactive/docs/gallery/geomap#markers-example gibts zwar n beispiel für lat/lng (format 1), aber ich hab mit der api auch noch nie was gemacht.

**Comment by SniperSister** [comment]
ok, ich versuch in den nächsten Tagen mal drauf zu schauen

**Comment by widmann-it** [comment]
Hat da Yves schon was mal geschrieben ;-)

**Comment by widmann-it** [comment]
https://demo.compojoom.com/hotspots

**Comment by chmst** [comment]
Oder unsere: im Beispiel hier: http://cbf-muenchen.de/karte-rolliwanderungen

**Comment by ufuk-avcu** [comment]
Die Demo von Compojoom gefällt mir sehr gut. Gibts auch for free. Ist halt die Frage, ob wir Erweiterungen von anderen verwenden wollen oder nicht...

**Comment by widmann-it** [comment]
Gibt es hierzu schon einen Lösungsansatz ?

**Comment by chmst** [comment]
Es sind ja nicht viele Adressen. Ich könnte mal eine Musterkarte erstellen, muss ohnehin die Änderungen für die Google map api key neu durchtesten. Dann könnt ihr sehen, ob euch das zusagt.

**Comment by chmst** [comment]
Gab leider mal wieder eine Verzögerung ... welche Daten wollen wir bei den einzenen JUG anzeigen? Nur eine Karte mit Link wie bisher? Oder auch Ansprechparnter und anderes?

**Comment by SniperSister** [comment]
Ich würde es beim Link belassen - die Angabe ist zeitlos ;)

**Comment by chmst** [comment]
Ich hab mal eine map mit ein paar markern eingerichtet. http://jug-demo.chmst.de/ 
Ist auf das absolute Minimum reduziert. Wer will darf auch (ohne Doku ...) Adressen eintragen.

**Comment by chmst** [comment]
demo jugdemo

**Comment by widmann-it** [comment]
Bitte schaut euch die Demo an - Wenn nichts dagegen Spricht würden wir mit der Umsetzung auf joomla.de beginnen.

**Comment by SniperSister** [comment]
Keine Einwände von meiner Seite.

**Comment by widmann-it** [comment]
ist Erledigt
