### ISSUE TITLE
JUG Oldenburg in verschärfter Beobachtung halten 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#121]
Die JUG ist wohl inaktiv, es werden aber automatisch neue Termine generiert. Markus Wortmann hat sich der Sache nach Telefonischer Rücksprache angenommen.

**Comment by ufuk-avcu** [comment]
Gibt es hierzu Neuigkeiten?

**Comment by widmann-it** [comment]
JUG Oldenburg wurde entfernt
