### ISSUE TITLE
Frage - Messetermine mit veröffentlichen 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#122]
Derzeit werden keine Messetermine mit veröffentlicht, es wäre jedoch ein guten Zug den möglichen Anwendern auch außerhalb der Regionalen Veranstaltungen auch die CMS-Garden Termine zu nennen ? Was sagt Ihr dazu ?

**Comment by SniperSister** [comment]
Fokus also auf den Garden? Da hätte ich kein Problem mit :)

**Comment by widmann-it** [comment]
Ja zum Beispiel

**Comment by SniperSister** [comment]
Zum Beispiel oder im speziellen? Hätte hier gerne eine klare Grenze was gelistet wird und was nicht.

**Comment by widmann-it** [comment]
Ja nur um den Garden, alles andere bringt nichts. Hatte noch an die Termine bzw. bei uns in Region an Veranstaltungen wie Webmontag oder WebSom gedacht, aber das geht ja weniger vom Verein aus  .

**Comment by widmann-it** [comment]
Auf später verschoben - CMSGarden Termine mit rein nehmen.
