### ISSUE TITLE
Anpassung http://www.joomla.de:443/administrator/

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#123]
Aufruf anpassen

**Comment by SniperSister** [comment]
Das issue hier brauch mehr Details, verstehe nur Bahnhof

**Comment by widmann-it** [comment]
Sorry zu schnell gewesen. beim Aufruf https://www.joomla.de/administrator nach der Eingabe des "admin" Passwortes erscheint die url. http://www.joomla.de:443/administrator/

**Comment by SniperSister** [comment]
Welchen Browser nutzt du? Betriebssystem? Cache geleert? Kann das hier nicht reproduzieren.

**Comment by widmann-it** [comment]
Egal welcher Browser Problem tritt immer auf wenn ich mich einwähle, ändere dann den Text in der Browserzeile ab und dann klappt es. Wohl ein Fehler bei der Weiterleitung von der htacces

**Comment by SniperSister** [comment]
Ich kann das hier leider nach wie vor nicht nachvollziehen - irgendwer sonst @JandBeyond/joomla-de?

**Comment by dneukirchen** [comment]
Bei regulären Aufrufen nicht. Wenn ich den link hier benutze, schon: [https://www.joomla.de/administrator](https://www.joomla.de/administrator) 

EDIT: zumindest heut mittag. Jetzt bekomme ich n  ERR_EMPTY_RESPONSE

**Comment by SniperSister** [comment]
Aaaaahh, got it! @tecpromotion kannst du da mal drauf schauen? sieht mir persönlich nach Hosting-Heckmeck aus.

**Comment by ufuk-avcu** [comment]
Das Problem scheint nun gelöst zu sein. Bei mir geht es inzwischen ohne Problem. Allerdings muss ich den htaccess Schutz zweimal eingeben...

**Comment by widmann-it** [comment]
dto. Problem tritt nicht mehr auf
