### ISSUE TITLE
Mod JVersion verwendet immer den letzten Release

### ISSUE THREAD

**Issue by dneukirchen** [JandBeyond/joomlade#125]
Das kann jedoch auch ein rc oder ne beta sein. 
Hier muss die Logik noch geändert werden (am besten vor 3.6rc) ;)

**Comment by zero-24** [comment]
Wo ist denn der Code für JVersion? im joomlade repo hab ich nichts gefunden.

Ich gehe in einem ähnlichen Plugin auf die update Server von update.joomla.org da gibt es eine feste Datei wo immer die aktuelle Version samt Download drin steht.

Github:
https://github.com/joomla/update.joomla.org/blob/master/www/core/sts/list_sts.xml

update.joomla.org
https://update.joomla.org/core/sts/list_sts.xml

ggf. kann man über die Version die man dort bekommt den Full download bei Github abfragen?

**Comment by dneukirchen** [comment]
https://github.com/JandBeyond/joomlade/tree/master/src/modules/mod_jversion

Müssen master und dev mal wieder syncen :(

und clean https://github.com/dneukirchen/mod_jversion

**Comment by zero-24** [comment]
Es gibt ne API hier: https://developer.github.com/v3/repos/releases/ aber anscheinen nicht für api.github.com sondern irgendwie anders (anscheinend) ggf. hilft JGithub aber das habe ich mir noch nicht angeguckt.

**Comment by dneukirchen** [comment]
JGithub hat leider den entsprechenden endpunkt (releases) nicht.

Ich glaube dein PR allein reicht noch nicht aus, da wir dort den single resource endpunkt /releases/latest nutzen und nicht über die releases iterieren.

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/github/package/repositories.php

bzw. JGithub: https://github.com/joomla/joomla-cms/tree/staging/libraries/joomla/github

**Comment by zero-24** [comment]
oops stimmt hab den falschen link. ... gibt doch nichts da. hmm aber die API bei github gibt es.

**Comment by zero-24** [comment]
Hier das könnte helfen: https://github.com/joomla-framework/github-api/blob/master/src/Package/Repositories/Releases.php

Aber das ist im Framework und noch nicht im CMS ggf. muss man sich das selbst stricken oder direkt die Framework Version nehmen.

**Comment by dneukirchen** [comment]
Jo... oder 5 Zeilen mit JHttp. Das sind doch eh alles nur convenience wrapper ohne wirklichen Mehrwert, oder? Werd heute abend mal schauen, wie wir das rc/beta problem am besten gelöst bekommen.

**Comment by dneukirchen** [comment]
Sind alle rc/beta releases immer als pre-release getagged? @zero-24

**Comment by zero-24** [comment]
> Sind alle rc/beta releases immer als pre-release getagged?

@dneukirchen ja.

> Das sind doch eh alles nur convenience wrapper ohne wirklichen Mehrwert, oder? 

weiß ich nicht. das hier funktioniert nicht im browser: https://api.github.com/repos/joomla/joomla-cms/releases/3.5.0

**Comment by dneukirchen** [comment]
Dann lasse ich einfach https://api.github.com/repos/joomla/joomla-cms/releases durch ne schleife laufen und nehme den ersten nicht pre-release.

**Comment by dneukirchen** [comment]
Oder: https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name

Is besser, weil ich dann nicht so unendlich viele daten ziehen muss.

**Comment by zero-24** [comment]
:+1: so nen URL hatte ich gesucht aber nicht gefunden.

Oder
https://api.github.com/repos/joomla/joomla-cms/releases/tags/3.5.0

und dann mit dem wert aus der update.joomla.org XML :smile:

**Comment by dneukirchen** [comment]
jo, genau. Baue das nachher ein.

**Comment by dneukirchen** [comment]
Sollte dann damit behoben sein: 
https://github.com/JandBeyond/joomlade/commit/56154c77e61f7b2480c72ab00e63e12c98ed9bb0
