### ISSUE TITLE
Start & Endbildschirm machen 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#127]
Brauche noch für die Videoproduktion den Start bzw. Endbildschirm

**Comment by ufuk-avcu** [comment]
Hast du eine Vorstellung wie das sein soll? Möchtest du es eher so haben, das es mit einem Bild beginnt: https://www.youtube.com/watch?v=8w26WJBUa2k
oder mit einem einfachen Text, wie hier: https://www.youtube.com/watch?v=LmRbijl5luM ?

**Comment by widmann-it** [comment]
Am Start und Ende das Logo des Vereins als Vollbild alle anderen Informationen etc. werden von der Videosoftware gesetzt. 

Original Message processed by david®  
Re: [JandBeyond/joomlade] Start & Endbildschirm machen (#127) (15-Jun-2016 12:22)
From:   Ufuk Avcu
To:JandBeyond/joomlade
Cc (2):Author, widmann-it

Hast du eine Vorstellung wie das sein soll? Möchtest du es eher so haben, das es mit einem Bild beginnt: https://www.youtube.com/watch?v=8w26WJBUa2k
oder mit einem einfachen Text, wie hier: https://www.youtube.com/watch?v=LmRbijl5luM ?

**Comment by ufuk-avcu** [comment]
Ich glaube der Verein hat kein (richtiges) Logo: http://www.jabev.de/

**Comment by widmann-it** [comment]
Dann das joomla logo mit dem hinweis das es von der deutschen Community kommt

Original Message processed by david®  
Re: [JandBeyond/joomlade] Start & Endbildschirm machen (#127) (15-Jun-2016 12:28)
From:   Ufuk Avcu
To:JandBeyond/joomlade
Cc (2):Author, widmann-it

Ich glaube der Verein hat kein (richtiges) Logo: http://www.jabev.de/ueber
