### ISSUE TITLE
Admin Login immernoch ein Problem

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#135]
Hey, 
das Loginproblem besteht immer noch ! 
Vorgehensweise :
https://www.jooomla.de/administrator
Abfrage kommt und die Daten werden hinterlegt - Enter 
Jetzt kommt die Meldung 404 (firefox) 
Es wird versucht die Adresse http://joomla.de:443/administrator versucht aufzurufen ! 
Nun wird in die Adressleiste nochmal die Anforderung von oben eingeben, es erscheint die htacess Abfrage wieder und im Anschluss kann man sich Anmelden.

**Comment by zero-24** [comment]
Vielleicht ein Problem der .htaccess? @SniperSister @tecpromotion ?

**Comment by widmann-it** [comment]
Danke Tobias :-) Wollte ich auch gerade schreiben ;-)

**Comment by SniperSister** [comment]
@tecpromotion Ich habe mal:
- Force SSL in der Joomla Konfig rausgenommen
- htaccess im Root rausgenommen
- htaccess im /administrator rausgenommen

Keine Änderung, sieht mir nach nem Mittwald Problem aus

**Comment by widmann-it** [comment]
Mittlerweile behoben
