### ISSUE TITLE
Anzahl der Administratoren 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#136]
Wir haben eine Vielzahl an Administratoren die sich seit fast einem Jahr nicht mehr angemeldet haben. Ich würde diese gerne auf Inaktiv setzen wenn keiner was dagegegen hat.

**Comment by SniperSister** [comment]
Nö, raus damit

**Comment by widmann-it** [comment]
Erledigt, Benutzer wurden Deaktiviert
