### ISSUE TITLE
Beim Backup kommt eine symlink Warnung

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#142]
symlink /html/joomla/media/plg_system_kickcck points to a file or folder that no longer exists and will NOT be backed up.

ggf kann man den symlink löschen @nielsnuebel ?

**Comment by zero-24** [comment]
Wurde auf der Hütte durch @nielsnuebel behoben :smile:

**Comment by SniperSister** [comment]
Könnt ihr noch kurz dokumentieren was ihr geändert habt?

**Comment by zero-24** [comment]
ich gehe davon aus das der symlink gelöscht wurde?
