### ISSUE TITLE
Video Anbindung geht nicht mehr

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#144]
Unter "Wissen" wird der Menüpunkt "JDay Videos" nicht angezeigt

**Comment by zero-24** [comment]
Richtig ist aktuell versteckt. Da zumindest mir nicht klar ist ob und wenn ja wie wir das starten ;)

**Comment by widmann-it** [comment]
Sehr gut versteckt ;-) Der Link geht nicht

**Comment by zero-24** [comment]
Hmm muss ich mir später mal ansehen. Ich hatte nur den menüpunkt versteckt?

**Comment by widmann-it** [comment]
erledigt

**Comment by zero-24** [comment]
Woran lag es? CSS?
