### ISSUE TITLE
Verfasser der Newsbeitrages einbinden 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#151]
In der Marketing Gruppe haben wir besprochen das der Verfasser des Berichtes genannt wird. 
Hierfür soll der Autorname verwendet werden. Wer kann das übernehmen ?

**Comment by drmenzelit** [comment]
Fürs Magazin hat Barbara es schon gemacht. Welche andere Bereiche sollen übernommen werden? Aktuelles? Die Adventsaktion? Wo noch?

**Comment by widmann-it** [comment]
Aktuelles & Adventkalender

**Comment by drmenzelit** [comment]
Aktuelles ist gemacht. Beim Adventskalender habe den Titel des Menüs geändert (wie besprochen)., Autor wird hier nicht angezeigt, weil nur das Bloglayout gibt :-)

**Comment by widmann-it** [comment]
OK, danke Vivanne
