### ISSUE TITLE
Joomladay 2017 Banner 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#154]
hier ist noch das alte Banner

https://www.joomla.de/events/joomladay

**Comment by drmenzelit** [comment]
Soll hier das Early Bird Banner rein?

**Comment by widmann-it** [comment]
ja, wir müssen nur daran denken das wir es dann austauschen, bitte Lokal auf den joomla.de Server ablegen :-) Habe gerade ein weiteres Issue aufgemacht

**Comment by drmenzelit** [comment]
ist drin

**Comment by widmann-it** [comment]
Danke
