### ISSUE TITLE
Firefox meldet nach letzten Update das die Seite unsicher ist

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#156]
Nacchdem letzten Update des Firefox meldet dieser das die Webseite unsicher ist. 
Das Problem hängt mit dem Nachladen der Banner von anderen Webseiten zusammen. 
Empfehlung die Banner Lokal einbinden das eine durchgängige SSL Verschlüsselung gewährleistet ist.

**Comment by drmenzelit** [comment]
Banners sind jetzt alle von lokal eingebunden

**Comment by widmann-it** [comment]
Danke
