### ISSUE TITLE
Pressebereich Anlegen 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#157]
Die Presseberichte müssen auf der Webseite eingebunden werden ;-)

**Comment by widmann-it** [comment]
Link "Presse" im Hauptmenü angelegt

**Comment by widmann-it** [comment]
Wer kümmert sich darum das die Presseberichte auch erscheinen ;-)

**Comment by widmann-it** [comment]
Grafische Aufarbeitung gewünscht ;-)

**Comment by widmann-it** [comment]
Nadine kümmert sich um Artikel :-)

**Comment by zero-24** [comment]
@widmann-it was möchtest du von mir? Also das du mich assigned hast? Oder hat sich das mit der discussion heute alles erledigt?

**Comment by zero-24** [comment]
@widmann-it Kann geschlossen werden?
