### ISSUE TITLE
Menüpunkt Tipps anpassen 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#158]
Advent rausnehmen

**Comment by widmann-it** [comment]
erledigt

**Comment by SniperSister** [comment]
Sind die Inhalte dahinter noch erreichbar? Die sind ja im google Index und sollten jetzt nicht einfach in nen 404 laufen

**Comment by drmenzelit** [comment]
Marc meinte Advent rausnehmen im Name des Menüs:
vorher JoomlaTipps im Advent
jetzt Joomla Tipps und Tricks.. der Alias hat sich nicht geändert

**Comment by SniperSister** [comment]
Super, wenn der alias bleibt ist alles gut
