### ISSUE TITLE
Weblinks Updateserver 

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#159]
Bitte den Updateserver für Weblinks hinzufügen

INSERT INTO `#__update_sites` (`name`, `type`, `location`, `enabled`) VALUES
('Weblinks Update Site', 'extension', 'https://raw.githubusercontent.com/joomla-extensions/weblinks/master/manifest.xml',1);

Da wir noch auf einer alten Version von weblinks sind und der Updateserver fehlt zum updaten ;)

**Comment by SniperSister** [comment]
Done!

**Comment by zero-24** [comment]
Danke. Weblinks Update ist durch
