### ISSUE TITLE
Design > Megamenü: Modul unter "Community"

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#16]
Teaserbild mit Schlagworten gestalten, oder andere Idee?
Super wäre ein Video (Zukunftsgedanke)

**Comment by a-fusion** [comment]
Meinst du mit Teaserbild die Slideshow? Falls ja: Auch dort hätte Radek Videomaterial soviel ich weiß. Ich kann ihm mal fragen, falls ich das richtig verstehe...?

**Comment by coolcat-creations** [comment]
Hallo Alex, nein ich meine das Modul im Megamenü unter Community (Siehe Titel ;-) hihi

**Comment by coolcat-creations** [comment]
![menue](https://cloud.githubusercontent.com/assets/828371/9043775/172b0746-3a18-11e5-803e-c84e52fcab88.jpg)
