### ISSUE TITLE
[Dienstleister] Design Vorschlag für Dienstleister Verzeichnis

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#161]
Für das Dienstleister Verzeichnis brauchen wir Design Vorschläge für folgende Seiten 

Seiten
- Registrierung
- Liste der Dienstleister
- Einzelansicht Dienstleister
- Eintrag Bearbeitungsseite (nur Reiter Profil)

**Comment by zero-24** [comment]
# Aktuelles aussehen

### Registrierung

![image](https://cloud.githubusercontent.com/assets/2596554/25020340/37ee2c7a-208e-11e7-9132-2968c8c8f4a0.png)


### Liste der Dienstleister

![image](https://cloud.githubusercontent.com/assets/2596554/25020278/f6be7f20-208d-11e7-8328-702e2bdfb073.png)


### Einzelansicht Dienstleister

![image](https://cloud.githubusercontent.com/assets/2596554/25020303/0e77f808-208e-11e7-9140-27f3ee7bb85a.png)


### Eintrag Bearbeitungsseite (nur Reiter Profil)

![image](https://cloud.githubusercontent.com/assets/2596554/25020379/56bae238-208e-11e7-8ce8-9cb62fb994d2.png)

**Comment by widmann-it** [comment]
Habe nicht einzuwenden  ;-) Können wir so übernehmen von meiner Seite aus

**Comment by SniperSister** [comment]
Lukas reicht da nochmal aktuelle Entwürfe nach

**Comment by svom** [comment]
![bildschirmfoto 2017-04-20 um 12 35 03](https://cloud.githubusercontent.com/assets/14434412/25229093/2b26c8bc-25cf-11e7-84d5-4b84b83bfbc4.png)
![bildschirmfoto 2017-04-20 um 12 35 25](https://cloud.githubusercontent.com/assets/14434412/25229091/2b1e554c-25cf-11e7-9601-21bb7966bd46.png)
![bildschirmfoto 2017-04-20 um 12 35 49](https://cloud.githubusercontent.com/assets/14434412/25229092/2b1f3b42-25cf-11e7-89cf-39a8d5a219d2.png)

**Comment by zero-24** [comment]
Kannst du privatsfähre einstellungen + die normalen einstellungen (also die tabs im frontend edit view) entfernen. Die sind für unseren usecase von wickedteam nicht notwendig und macht die GUI nochmal einfacher :)

Hattest du das kein logo ding und den edit / unpublished info sachen mit berücksichtigt?

**Comment by svom** [comment]
Holla,

Kannst du privatsfähre einstellungen + die normalen einstellungen (also die tabs im frontend edit view) entfernen. Die sind für unseren usecase von wickedteam nicht notwendig und macht die GUI nochmal einfacher :)

Sind rausgeworfen.

Wenn kein Logo hochgeladen wird, dann wird einfach der Name angezeigt vom entsprechenden Unternehmen (s. Screenshot.).

Was meinst du mit den edit/unpublished info sachen?

![bildschirmfoto 2017-04-20 um 16 40 19](https://cloud.githubusercontent.com/assets/14434412/25236409/110c2788-25e8-11e7-9e1e-4e65d5d6b91e.png)

**Comment by zero-24** [comment]
Den edit link für den admin :) also der edit button :)

**Comment by svom** [comment]
Der ist doch oben links drin jeweils. Oder meinst noch einen anderen?

**Comment by zero-24** [comment]
Ahh ich bin blind. Danke! Kannst du die Overrides als PR schicken?

**Comment by zero-24** [comment]
Danke PR war #169

**Comment by drmenzelit** [comment]
Bei dem Edit Formular fehlen die Icons neben dem Logo Feld bzw. sind noch nicht in FontAwesome ungestellt: icon-image und icon-trash

**Comment by zero-24** [comment]
kannst du dafür eine PR gegen master machen?

**Comment by drmenzelit** [comment]
Wenn ich wüsste wo die her kommen...

**Comment by zero-24** [comment]
hmm dann mach bitte einen neuen issue auf mit screenshot und was genau geändert werden muss. Dann schaue ich mir das später mal an 👍

**Comment by drmenzelit** [comment]
Ich habe eine PR geschickt... gelöst mit CSS. Ich  kann die nur gegen dev machen...

**Comment by zero-24** [comment]
👍
