### ISSUE TITLE
[Dienstleister] Dienstleisterfreigabeteam Beschreibung

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#165]
Welche Administrativen schritte sind zur Freigabe notwendig.

**Comment by SniperSister** [comment]
Prüfung "gültiger Link"
Prüfung Texte (keine Rechtsverstöße etc.)
Prüfung "hat Eintrag im JRD"

Was fehlt?

**Comment by zero-24** [comment]
Ja das ist der Plan. und dazu kommt noch ein kurzer text / Beschreibung wie man das ganze freigibt.

**Comment by zero-24** [comment]
aber wir sollten den Prozess dokumentieren das er für alle nachvollziehbar ist :)

**Comment by zero-24** [comment]
Schon von @drmenzelit https://github.com/JandBeyond/joomlade/wiki/Dienstleister-Verzeichnis erledigt 👍
