### ISSUE TITLE
Aufbau der Dankesseite für die Community 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#166]
Ich würde gerne eine Dankesseite für die Unterstützung der deutschen Community machen, wo alle Helfer genannt werden die sich in einen der vielen Bereichen für das Joomla Projekt einsetzen. 

Vorschläge und bitte Namen 
David Jardin
Robert Deutz
Stefan Wendhausen
Tobis Zulauf
Nadine Huss Schäfer
Vivianna Menzel
Babara Assmann
Bejanjamin Trenkle
Thilo Petry
David Neukirchen 
Christiane Maier-Stadtherr
Yves Hoppe
Guido De Gobbis
Tom Möller
Astrid Günther
Sigrid Gramlinger
Ufuk Avcu
Robert Mittl
Christian Schmitt
Markus wortmann
Markus Linne
Alexander Metzler
Patrick Jungbluth
Andre Dreier
Christian Hent
Dirk Haeuser
Mike Brandner
Holger
Frank .... Hamburg 1
Niels B. 
Elisa F.
Christian Hamberger
Frank Schumann
Toni Gerns
usw.

**Comment by SniperSister** [comment]
Wäre das "nur" eine Namensliste? Was wäre das Kriterium für die Aufnahme?

**Comment by widmann-it** [comment]
Nur eine Namensliste, Alles andere wäre der Aufwand nicht gerechtfertigt. Auf joomla.org zu verweisen halte ich für schlecht, zwar sind dort eine Vielzahl der Helfer hinterlegt. Es fehlen aber einige die sich in einem kleinen Feld bewegen und zum Teil nicht über diesen Bereich hinausgeht

**Comment by widmann-it** [comment]
Das Kriterium wäre er hilft in der Community

- Als Programmierer
- In den JUGS
- Marketing Team
- usw.
- oder in sonst einer Weise innerhalb des Projekts im Bereich D-A-CH

**Comment by SniperSister** [comment]
Ok, bei meiner Namensliste sehe ich kein Problem, wenn da auch andere "Vorteile" (insb. Links) dabei gewesen wären, hätte das wohl Begehrlichkeiten geweckt.

**Comment by widmann-it** [comment]
Man kann sich Überlegen diejenigen die in Joomla.org gelistet sind einen Link zu versehen 😊 Vielleicht schafft es auch einen Anreiz sich dort einzutragen und ggf. dem Projekt anzuschließen 😊

**Comment by chmst** [comment]
https://www.joomla.org/3/thank-you das ist die von den Landing Pages, mit ein paar Zwischenüberschriften

**Comment by widmann-it** [comment]
Wer kann as Bild auf Deutschübersetzen ?

**Comment by zero-24** [comment]
@widmann-it sollten wir nicht lieber eins nehmen was unserem seiten design entspricht?

**Comment by drmenzelit** [comment]
Ich habe ein Paar Korrekturen (Kommas und Namen) vorgenommen.

**Comment by widmann-it** [comment]
Ich habe die Seite Überarbeitet und angepasst.
Nur für eingeloggte User Sichtbar !
https://www.joomla.de/danksagung-an-die-communitiy

**Comment by widmann-it** [comment]
Ist öffentliuch
