### ISSUE TITLE
[mod_jversion] Richtige Download Zahle anzeigen (downloads.joomla.org)

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#167]
Der aktuelle code spricht die github api an. Aktuell wird Joomla aber über downloads.joomla.org verteilt.

Daher müssten wir den code umbauen das er die downloads.joomla.org api nutzt. Siehe doku:
https://downloads.joomla.org/api-docs/

Es gibt aber laut doku noch keine versions spezifische API sondern nur counts for branch also 3.x / 2.5 / 1.5. etc.

IIRC wurde dafür aber was gebaut. ich hab das ganze mal bei Michael Babker nachgefragt wie da der stand ist.

cc: @dneukirchen

**Comment by zero-24** [comment]
@dneukirchen API endpoint ist: https://downloads.joomla.org/api/v1/downloads/cms/30 da kommt ein JSON mit allen 3.x versionen zurück und wir können uns den download count für die aktuelle version auslesen.

**Comment by dneukirchen** [comment]
Kümmer mich drum. Danke dir!

**Comment by dneukirchen** [comment]
V2 nutzt die neue api, kann gerne getestet werden. Erstelle dann danach einen PR in diesem repo: 
https://github.com/dneukirchen/mod_jversion/tree/2.0.0

**Comment by zero-24** [comment]
@dneukirchen sieht gut aus. kannst du die PR machen?

**Comment by dneukirchen** [comment]
jo, kommt am we.

**Comment by zero-24** [comment]
danke! :+1:

**Comment by dneukirchen** [comment]
Mache zu #186
