### ISSUE TITLE
[Content] Joomla.org Roadmap übersetzen

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#168]
Unter https://developer.joomla.org/roadmap.html wurde ein neues "lebendes dokument" angelegt was immer den aktuellen stand der roadmap wiederspiegel soll.

Macht es sinn das zu übersetzen und auf joomla.de zuveröffentlichen?

Idee von @dneukirchen

**Comment by drmenzelit** [comment]
Mike Brandner hat sich freiwillig gemeldet

**Comment by coolwebcreations** [comment]
Hier findet Ihr die Übersetzung (noch nicht vollständig)
https://github.com/m-b-o/joomlade/blob/master/roadmap/doc.txt

**Comment by zero-24** [comment]
:+1: Sieht schon mal gut aus.

**Comment by tecpromotion** [comment]
Dürfte alt sein -> closed
