### ISSUE TITLE
Dev > Megamenü: Modul unter "Veranstaltungen"

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#17]
Hier den DP(?) Kalender einfügen mit Verlinkung zur jeweiligen Veranstaltung. Ist hier eine Unterscheidung zwischen zwischen JUG, Joomladay usw per icon oder ähnliches möglich?

**Comment by coolcat-creations** [comment]
Ich habe den GCalendar eingebunden (siehe alte joomla.de) Seite - Aber die Lösung ist eher schlecht als recht und außerdem ist GCalendar schon 2 Jahre alt und wird nicht weiterentwickelt.
Gibt es jemanden der die Termine irgendwie von Google "holen" kann? Hilft das: http://mikeclaffey.com/google-calendar-into-html/ weiter? Das ist mir leider zu hoch :)

**Comment by ufuk-avcu** [comment]
Entweder muss dann DPCalender her oder wie David es gesaght hat ein Plugin der die Google Calender API abholt.

**Comment by SniperSister** [comment]
Ich mache ein Plugin

**Comment by coolcat-creations** [comment]
Hab vorübergehend den Joomladay eingefügt aber ein plugin wäre immernoch viel besser - dann wahrscheinlich am Sprint oder Notfalls für Version 2.0

**Comment by SniperSister** [comment]
Done
