### ISSUE TITLE
[Repo] Wofür brauchen wir noch die dev branch?

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#172]
Wofür brauchen wir noch die dev branch? bzw wofür war die mal gedacht? Aktuell mergen wir alles in dev und müssen dann dev und master syncen. warum nicht direkt alles über den master machen welcher sich dann mit dem server synchronisiert?

**Comment by SniperSister** [comment]
Ursprünglich wollten wir uns mal ein Staging / Live Setup zulegen, hat sich aber wohl im Betrieb erledigt

**Comment by zero-24** [comment]
ok, danke. `master` ist jetzt default und dev ist gelöscht. 👍
