### ISSUE TITLE
Zwei unbekannte Benutzer Gruppen

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#174]
![image](https://cloud.githubusercontent.com/assets/2596554/25306912/e881e67a-2797-11e7-93ac-14c8169632b8.png)

Was hat es mit diesen zwei Benutzergruppen auf sich? Können die gelöscht werden? Oder werden die noch irgendwo benötigt (und sind deshalb noch nicht gelöscht worden)?

**Comment by widmann-it** [comment]
Kannst die entfernen ;-) Die wurden am Anfang mal angelegt aber meines Wissens nie genutzt

**Comment by zero-24** [comment]
die nicht nutzen 2 kann ich löschen.

die nicht nutzen 1 muss auf der Datenbank gemacht werden.

ich bekomme da den Fehler:
![image](https://cloud.githubusercontent.com/assets/2596554/25316295/d94c2eb8-2864-11e7-83f2-28c094ef92c6.png)

**Comment by zero-24** [comment]
ok liegt daran das das löschen von #__usergroups mit parent_id 0 nicht erlaubt ist da das normalerweise "öffentlich" ist.

Bitte also folgendes SQL auf der Datenbank ausführen welches quasie diese Tabelle neu aufbaut:
```sql
DROP TABLE IF EXISTS `#__usergroups`;

CREATE TABLE IF NOT EXISTS `#__usergroups` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `parent_id` int(10) unsigned NOT NULL DEFAULT 0 COMMENT 'Adjacency List Reference Id',
  `lft` int(11) NOT NULL DEFAULT 0 COMMENT 'Nested set lft.',
  `rgt` int(11) NOT NULL DEFAULT 0 COMMENT 'Nested set rgt.',
  `title` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_usergroup_parent_title_lookup` (`parent_id`,`title`),
  KEY `idx_usergroup_title_lookup` (`title`),
  KEY `idx_usergroup_adjacency_lookup` (`parent_id`),
  KEY `idx_usergroup_nested_set_lookup` (`lft`,`rgt`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

INSERT INTO `#__usergroups` (`id`, `parent_id`, `lft`, `rgt`, `title`) VALUES
(1, 0, 1, 18, 'Public'),
(2, 1, 8, 15, 'Registered'),
(3, 2, 9, 14, 'Author'),
(4, 3, 10, 13, 'Editor'),
(5, 4, 11, 12, 'Publisher'),
(6, 1, 4, 7, 'Manager'),
(7, 6, 5, 6, 'Administrator'),
(8, 1, 16, 17, 'Super Users'),
(9, 1, 2, 3, 'Guest');
(10, 2, 15, 14, 'Dienstleister');

UPDATE `#__user_usergroup_map` SET `group_id` = '10' WHERE `group_id` = 12;
```

cc @SniperSister

**Comment by SniperSister** [comment]
Manuelles Reparieren eines Nested Sets 💪 

Done!

**Comment by zero-24** [comment]
Danke.
