### ISSUE TITLE
Super Administratoren

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#175]
Wir haben eine ganze Reihe an Superadministratoren die sich entweder noch nie oder zuletzt 2016 angemeldet haben.

Spricht etwas dagegen die bis auf weiteres zu löschen (können Ja immer wieder neu erstellt werden) (diese Accounts sind bereits deaktivert)?

Da diese Accounts schon deaktivert sind und sich bis jetzt keiner dazu gemeldet bzw. darüber beschwert hat?

**Comment by SniperSister** [comment]
Keine Einwände von mir

**Comment by zero-24** [comment]
Erledigt.
