### ISSUE TITLE
[Dienstleister] Modul mit der Erklärung der Farben auf der Maps seite

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#176]
Auf der Seite wo die Dienstleister Map dargestellt werden soll sollte ein custom modul erstellt werden woran man sehen kann welche Farbe für welchen Haupttätigkeitsbereich steht.

**Comment by drmenzelit** [comment]
Ich habe ein Modul vorbereitet. Zu sehen neben der Dienstleister-Karte.

**Comment by zero-24** [comment]
👍 Sieht super aus!
