### ISSUE TITLE
[Repo] Milestones auf Github vs. Projecte?

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#177]
Wofür werden aktuell die Milestones auf Github genutzt? ggf. macht es mehr Sinn das ganze als Projekte zu gliedern? Der Issue XXX fehlt noch oder dabei XXX brauchen wir noch hilfe für XXX meiner Meinung nach viel einfacher.

**Comment by widmann-it** [comment]
Also Milestones sind unrelevant weder 1.0 noch 2.0 sind Aktiv bearbeitet worden, da macht es Sinn in Projekt auszugliedern :-)

**Comment by zero-24** [comment]
Ok dann kümmere ich mich darum wenn ich wieder zuhause bin.

**Comment by zero-24** [comment]
Alle Milestones sing geschlossen. und alle offenen issues von den milestones entfernt. Um das zuweisen der Projekte kümmere ich mich die Tage.

**Comment by zero-24** [comment]
Erledigt. Neue issues bitte in Zukunft einem Projekt zuweisen. Wenn etwas unklar ist gerne bei mir melden.
