### ISSUE TITLE
Design > Megamenü: Modul unter "Wissen"

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#18]
Eyecatcher-Banner mit Verlinkung zum Forum

**Comment by a-fusion** [comment]
Hey Elisa, diese Woche kümmere ich mich um die Issues. Was kann ich hier tun? Einen grafischen Vorschlag für die Darstellung der Megemenü?

**Comment by coolcat-creations** [comment]
![menue](https://cloud.githubusercontent.com/assets/828371/9043648/489d2c60-3a17-11e5-992b-9613309135b1.jpg)
Hier geht es um den gelben Platzhalter - da brauchen wir was schönes zum Auflockern des Menüs, also einen Eyecatcher. Es gab die Diskussion da ein paar Schlagworte abzubilden. Vielleicht gibt es noch eine andere Idee. DANKE!

**Comment by coolcat-creations** [comment]
Also das gleiche unter Wissen - habe den Screenshot für den falschen Menüpunkt gemacht aber im Grunde überall so...
