### ISSUE TITLE
[Dienstleister] Dienstleister als eigenen Hauptmenüpunkt? und oder auf der Startseite?

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#182]
Soll der neue Menüpunkt Dienstleister als "Hauptmenüpunkt" angelegt werden?
![image](https://cloud.githubusercontent.com/assets/2596554/25497519/279ea514-2b85-11e7-9c45-94165a4ce8ce.png)

Oder unter Community:
![image](https://cloud.githubusercontent.com/assets/2596554/25497568/59548650-2b85-11e7-88d1-d2e1e0a846c0.png)

![image](https://cloud.githubusercontent.com/assets/2596554/25497672/a951d32e-2b85-11e7-9bf9-615be2f04369.png)

Und oder sollen die Dienstleister prominent auf der Startseite platziert werden?
![image](https://cloud.githubusercontent.com/assets/2596554/25497646/987d8d18-2b85-11e7-9c52-e8e76a309372.png)

Oder passt ggf. ein anderer Platz noch besser?

**Comment by chmst** [comment]
voting for number one

**Comment by zero-24** [comment]
Nummer ein hat das Problem dass das Menü links raus fällt. Sprich entweder brauchen wir mehr CSS oder müssen uns etwas anderes überlegen.

ggf. gibt es ja noch etwas mehr Feedback.

**Comment by drmenzelit** [comment]
Erledigt
