### ISSUE TITLE
MyDocsLanguage Plugin

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#184]
Siehe #180 & #183 

ich hab das ganze mal in ein eigenes Repo gepackt. Initiales Release ist:

https://github.com/zero-24/plg_content_mydocslanguage
https://github.com/zero-24/plg_content_mydocslanguage/releases/tag/1.0.0

**Comment by SniperSister** [comment]
👍🏻

**Comment by zero-24** [comment]
live
