### ISSUE TITLE
Dev > "Fähnchen" Forum

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#19]
- Seitlich vom Menü mit fixed oder absoluter Position ein Link zum Forum
- Überlegung wie das im mobile View umgesetzt wird

![bildschirmfoto 2015-07-20 um 14 20 59](https://cloud.githubusercontent.com/assets/828371/8775651/91cbc96a-2eea-11e5-8603-b848230e80ea.png)

**Comment by SniperSister** [comment]
Das würde immer am rechten Bildrand kleben, oder?

**Comment by SniperSister** [comment]
Wie gehen wir denn dann mit dem Spaß um, wenn der Bildschirm schmaler wird und das Fähnchen eigentlich das Menü überlappen würde

**Comment by coolcat-creations** [comment]
Dann das Forum in das Menü packen? So wie jetzt? :)

**Comment by SniperSister** [comment]
Okay, und in der anderen Richtung? Wenn ich das hier auf die gesamte Bildschirmbreite ziehe hab ich 2440px in der Breite und das Fähnchen liegt komplett außerhalb des Blickfelds. Irgendwie bin ich von der Lösung noch nicht überzeugt :D

**Comment by webnet-assmann** [comment]
Forum 'Fähnchen' Link gestylt. css im branch aber noch nicht übernommen
