### ISSUE TITLE
[Dienstleister] Further Fields label in der Registrierung übersetzen 

### ISSUE THREAD

**Issue by SniperSister** [JandBeyond/joomlade#194]
![voila_capture 2017-07-10_07-58-33_pm](https://user-images.githubusercontent.com/498096/28032798-2696ca8c-65ac-11e7-8a1b-8f62f83e79f0.png)

**Comment by zero-24** [comment]
Override für den String: PLG_SYSTEM_WICKEDTEAMREGISTRATION_WICKEDTEAMFIELDS angelegt.
