### ISSUE TITLE
Design&Dev > Footer: Padding in mobiler Ansicht korrigieren

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#2]
padding hinzufügen in mobile view

**Comment by coolcat-creations** [comment]
Sorry, da checke ich den Code nicht so richtig 
"  margin-left: calc(~"(100vw - "@container-lg + @grid-gutter-width~") / 2 \* -1");"
ansonsten würde ich das selbst korrigieren

**Comment by SniperSister** [comment]
Was genau willst du denn da korrigiert haben? Stehe da auf der Leitung

**Comment by coolcat-creations** [comment]
![img_1469](https://cloud.githubusercontent.com/assets/828371/9438426/e72aa122-4a5d-11e5-896b-a349527522ca.PNG)
Die Schrift geht bis an den Rand am iPhone - ein bisschen Padding zu den Seiten hin wäre gut... Merci!!!
