### ISSUE TITLE
Content > Startseite > Slideshow

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#20]
Griffige Textvorschläge für jede Kategorie - bitte hier sammeln :-)

**Comment by webnet-assmann** [comment]
Was mir so einfällt:

Erstes Bild:
Joomla ist Open Source - 
Ein CMS für Alle

Zweites Bild:
Eine tolle Community -
Wir leben Open Source

Drittes Bild:
Termine rund um Joomla!
Austausch unter Gleichgesinnten

Viertes Bild:
Wissenswertes über Joomla!
(Von Spezialisten und Machern)       - da fällt mir nicht wirklich was ein...
