### ISSUE TITLE
Erstellen eines eigenen Eintrages geht nicht 

### ISSUE THREAD

**Issue by widmann-it** [JandBeyond/joomlade#200]
Vorarbeiten : 
- Neuen Nutzer für die Gruppe "Dienstleister" erstellen
- Im Frontend Anmelden 
- Über den Menüpunkt - Dienstleister - eigenen Eintrag gehen 

Jetzt kommt ein 403 Fehler
![modified](https://user-images.githubusercontent.com/13391650/30035017-dbaef726-91a5-11e7-98d8-0373215a3cb1.png)

**Comment by widmann-it** [comment]
Anderer Weg über Backend gegangen:

Über Komponenten > Wicked Team > Mitglieder > Neu 
Einen entsprechenden Eintrag von Hand hinterlegt.

Nachdem speichern des Eintrages ist dieser verschwunden (Unter Joomla Benutzer wurde der zuvor eingetragene neue Anwender hinterlegt)

**Comment by SniperSister** [comment]
Bitte nicht dran weiter basteln, gucke morgen drauf

**Comment by widmann-it** [comment]
Erledigt ! Falscher weg meinerseits ;-)
