### ISSUE TITLE
Dev > Coole Download Funktion für aktuelle Joomla Version

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#21]
Laut Roland Dalmulder gibt es ja die Funktion im Backend die checkt ob die aktuelle Joomlaversion installiert ist und wenn nicht, den aktuellen Link zur Verfügung stellt. Wenn man diese Funktion aufbohrt und "missbraucht" dann kann man den Joomla.de Besucher direkt zum Download schicken anstatt ihn von unserer Seite wegzuführen.

**Comment by coolcat-creations** [comment]
Aus Mangel an Kapazitität erstmal zurückgestellt - vielleicht etwas für die Zukunft...

**Comment by dneukirchen** [comment]
done
