### ISSUE TITLE
Chrome wird in Zukunft dem unter *joomla.de genutzen Zertifikten misstrauen

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#210]
https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html

Laut [Brian](https://github.com/joomla/joomla-websites/issues/1097#issuecomment-362945590) scheint der Google Chrome Canary dies schon umgesetzt haben.

@SniperSister @tecpromotion könnt Ihr das bitte nochmal auf nehmen? ggf. kann man LetsEncrypt einsetzen?

**Comment by SniperSister** [comment]
Das Zertifikat ist im Februar 2017 ausgestellt worden und daher von der ersten Maßnahme nicht betroffen sein.
