### ISSUE TITLE
Show Version J4 latest

### ISSUE THREAD

**Issue by tecpromotion** [JandBeyond/joomlade#215]
https://github.com/JandBeyond/joomlade/blob/c34977ca51e5f720559d3aac20e316d62d77658c/src/modules/mod_jversion/helper.php#L30-L33

**Comment by zero-24** [comment]
Gibt noch einen Upstream Fehler hier: https://github.com/joomla/downloads.joomla.org/issues/271

**Comment by zero-24** [comment]
Der Download counter API ist noch defekt.. https://github.com/joomla/downloads.joomla.org/issues/274

**Comment by zero-24** [comment]
Die Downloads API läuft nun und die Änderung wurde eingespielt: https://github.com/JandBeyond/joomlade/commit/e948c6804d26a54f442ad1c9464234174d119834

![image](https://user-images.githubusercontent.com/2596554/133888978-b617e5c3-5655-4642-bfc4-7747b20c6167.png)

![image](https://user-images.githubusercontent.com/2596554/133888986-2e3d7834-d994-431a-8cf9-13ec920aafe5.png)
