### ISSUE TITLE
Design > Blog Layout verbessern (#7)

### ISSUE THREAD

**Issue by drmenzelit** [JandBeyond/joomlade#23]
z.B. unter Aktuelles
- Titel nicht unterstreichen, Margin und Padding anpassen
- Tags stylen (Issue #8)
- margin-right bei den Thumbnails 
- Weiterlesen Button stylen (Issue #9?)
- Links (weitere Beiträge) unten mehr absetzen
- Seite 1 von ... nicht pull-right

**Comment by coolcat-creations** [comment]
Kann das mit #7 gemerged werden?

**Comment by drmenzelit** [comment]
Ja, hatte #7 übersehen :-)

**Comment by coolcat-creations** [comment]
gemerged - wenn man das so nennen kann ;)
