### ISSUE TITLE
Content > Joomla > Erweiterungen

### ISSUE THREAD

**Issue by drmenzelit** [JandBeyond/joomlade#25]
Link zu extensions.joomla.org sollte mit target blank definiert werden

Links zu Erweiterungstypen stimmen nicht... noch in Arbeit?

**Comment by webnet-assmann** [comment]
Links sind aktualisiert

**Comment by coolcat-creations** [comment]
Bei Sprachen fehlt ein n beim link :) dann kann der issue geschlossen werden
