### ISSUE TITLE
Design > Listen stylen

### ISSUE THREAD

**Issue by drmenzelit** [JandBeyond/joomlade#26]
Wie wäre es mit dem Joomla Logo als list-style-type? 

In Font Awesome gibt es schon als Icon:
<i class="fa fa-joomla"></i>

**Comment by coolcat-creations** [comment]
Wenn man dann irgendwann Listen mit 20 Punkten hat und überall ist das Joomla Logo davor... das wird wahrscheinlich zu überfrachtet aussehen...

**Comment by coolcat-creations** [comment]
erledigt
