### ISSUE TITLE
Content > Wissen

### ISSUE THREAD

**Issue by drmenzelit** [JandBeyond/joomlade#28]
Dieser Menüpunkt öffnet sich in einem neuen Fenster / Tab... so gewollt?

**Comment by coolcat-creations** [comment]
Nein, eher nicht - eventuell gab es noch keinen Content dazu? Bitte mit richtigen Inhalt verlinken :) @contentteam

**Comment by webnet-assmann** [comment]
Öffnet nun im gleichen Fenster
