### ISSUE TITLE
Content > Joomla > Features

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#32]
Hier fehlt noch eine Übersicht an mehr Features wie zum Beispiel:
Mehrsprachigkeit
Umfangreiche Supportmöglichkeiten
Einfache Updates
Intergriertes Hilfesystem
Mediamanager
Banner Management (noch erwähnen? evtl. wird das ja geschossen)
Kontaktverwaltung
Verschachtelte Kategorien
Tags
Frontendbearbeitung
Artikelversionierung
Syndication und Newsfeed Verwaltung
Menüverwaltung
Erweiterbarkeit
Rechtesystem
.... Für Designer
Entkoppeltes Design
Responsive mit Bootstrap
Less Support
Overrides
Schriften
Templateverwaltung
.... Für Entwickler
Userverwaltung
Microdata Bibliothek
Cloud Storage API
System Features
Webservices

.... Die Oberpunkte habe ich von dieser Seite hier: http://www.joomla.org/core-features.html
Vielleicht fällt Euch ja auch noch was dazu ein?

**Comment by coolcat-creations** [comment]
@ka3media Wir brauchen dringen den Input, kannst du etwas zur Verfügung stellen?

**Comment by SniperSister** [comment]
Super, denke das ist dann auch drin! Danke @designbengel und @webnet-assmann :)
