### ISSUE TITLE
Content > Joomla > Erweiterungen

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#33]
Im Text wird folgendes erwähnt:

Es gibt 5 Erweiterungstypen:
Komponenten
Module
Plugins
Templates
Sprachen

Die Links dazu funktionieren nicht. Sollte es Inhalte geben, bietet es sich an diese in einem Akkordion oder in Tabs auf der gleichen Seite abzubilden. Sofern es nicht so viel Text ist.

"Einige empfehlenswerte Erweiterungen:" sollten wir entweder vervollständigen oder komplett rausnehmen. Könnte zu "politisch" sein... Meinungen dazu?

**Comment by SniperSister** [comment]
Ich würde die Empfehlungen ganz raus lassen

**Comment by coolcat-creations** [comment]
ok, scheint aktualisiert zu sein :)
