### ISSUE TITLE
Content > Joomla > Showcase

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#35]
Inhalte fehlen, Screenshots, Links, Texte

**Comment by ufuk-avcu** [comment]
Soweit ich weiß, wollten wir explizit deutsche Webseiten? Wir könnten ja hier anfangen zu sammeln. Ich frage mal im D-A-CH Chat auf Glip und auf Facebook nach. Vielleicht finden sich so ganz gute Beispiele...

**Comment by widmann-it** [comment]
Denke das können wir dann nach der Veröffentlichung angehen

**Comment by tecpromotion** [comment]
closed
