### ISSUE TITLE
Dev > Startseite > Modul:Veranstaltungen in deiner Nähe

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#4]
- Chronologische Ausgabe der nächsten JUG Treffen, vorne mit PLZ Icon, siehe Gestaltungsvorschlag
- 3 Buttons mit Verlinkung zu: Alle anzeigen, Raum sponsorn, "JUG gründen"

**Comment by dneukirchen** [comment]
Kalender Modul ist erstellt und kann gestyled werden. 
- Die Events werden aus dem [Joomla.de Terminkalender](https://www.google.com/calendar/embed?src=36qt2q50uunhpokiuadk56g4eo%40group.calendar.google.com&ctz=Europe/Berlin) ausgelesen. 
- Die API Anfragen werden standardmäßig 60 Minuten zwischengespeichert (Kann in den Moduleinstellungen geändert werden).
- Die Darstellung kann über die Moduleinstellungen modifiziert werden. 
- Eine Kalenderansicht ist geplant, wurde aber aus zeitgründen erstmal verschoben. 
- Ein API key ist erforderlich. 1.000.000 Requests/Tag erlaubt. Mehr dazu: [Google Developer Console](https://console.developers.google.com)

**Comment by coolcat-creations** [comment]
Supercool David(s), könnt ihr mir ein override in den Template Ordner erzeugen damit ich das Styling übernehmen kann? Und falls noch nicht drinnen: habe ich eine Variable für jedes Element? z.B: PLZ ?
Merci!

**Comment by coolcat-creations** [comment]
@SniperSister

**Comment by dneukirchen** [comment]
Lege dir gleich ein override an. Du kannst mir aber auch gern kurz schreiben, welchen Modul Output du brauchst,  dann benötigen wir kein override. 

Leider ist es nicht bzw nicht ohne weiteres möglich die Bestandteile der Adresse (Str. PLZ etc) zu trennen, da sie von Google als zusammengesetzter Text geliefert werden.
