### ISSUE TITLE
Content > Community > JUGs

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#40]
- Formular zur Anmeldung einer neuen Usergroup
- Google(?) Karte mit Anzeige aller Usergroups, Umkreissuche (?)
- Link zu den Terminen (Bereich Veranstaltungen)
- Raumsponsoring ansprechen - Können Sie einen Raum zur Verfügung stellen? Bieten Sie Ihre Location für JUGs an... (oder so)

**Comment by coolcat-creations** [comment]
Bitte um kurzes Brainstorming :-)

**Comment by coolcat-creations** [comment]
Weitere Verbesserungen an JUG Unterseite für Meilenstein 2.0 verschoben (Bilder einfügen, Text anpassen, etc.)

**Comment by widmann-it** [comment]
Ist erledigt !
