### ISSUE TITLE
Content > Community > Dienstleister

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#43]
Karte Dienstleister mit Umkreissuche. Wer programmiert das? :-)

**Comment by coolcat-creations** [comment]
Den Punkt habe ich ausgeblendet -ok ?

**Comment by SniperSister** [comment]
Aktueller Diskussionsstand:
https://docs.google.com/document/d/1Zfg0-mIjcTPC5ZOaJGFuK4A0yHQ-Km4UjU5__mlubtA/edit

**Comment by SniperSister** [comment]
Finales "Konzept":

Welche Felder werden benötigt? 

Übersichtseite (Kategorie Leistung)
- Firmenname
- Logo
- Introtext, Max 500 Zeichen

Detailseite
- Firmenname (und ggf. Gesellschaftsform)
- Logo Feld
- Beschreibungstext Firma, Max 5000 Zeichen
- Adresse
- Straße
- Plz/Stadt
- Land (eventuell für D-A-CH)
- Kontakt
- Name
- Telefon
- Mail
- Website
- Angebotene Dienstleistungen (Kategorisierung, Tags)
- Karte (z.B. google Maps)
- Letzte Aktualisierung? Siehe unten -> Nachtrag
- Link zum Resources.Joomla.org Eintrag (nur für Mods sichtbar)

Welche Kategorien soll es geben?
- Gestaltungskonzept
- Consulting
- Text
- Design & Entwicklung
- Erweiterungsentwicklung
- Webhosting
- Joomla Security
- Marketing Support
- Migrationen & Upgrades
- Programmierung
- Projektmanagement 
- Training & Kurse
- Technischer Support
- Template Entwicklung

Workflow:
Ersteintragung: Anbieter trägt sich ein, Moderatorenteam schaltet frei

Wiederkehrend: Jährliches Update der Daten.
Ablauf > Dienstleister erhält eine Mail das er sich bitte einloggen soll und sein 
Account um ein weiteres Jahr verlängern soll. 14 Tage vor Ablauf wird er nochmal erinnert, 
sollte er auch an diesem Tag nicht verlängern, wird er gelöscht / unpublished.

**Comment by matrikular** [comment]
Any updates on this?

**Comment by nielsnuebel** [comment]
Soll es für jede Kategorie eine Karte mit Liste geben und kann ein Eintrag mehreren Kategorien zugeordnet werden?

Ich hätte sowas fertig, was ich bei Zeit umschreiben kann für Joomla.de! Muss aber noch das Video-Teil fertig machen.

**Comment by SniperSister** [comment]
Der @bembelimen hat das afaik fertig, braucht nurnoch ein bisschen Liebe in Sachen Optik

**Comment by nielsnuebel** [comment]
Alles klar.

**Comment by widmann-it** [comment]
Wer ist da gerade dran ?

**Comment by tecpromotion** [comment]
closed
