### ISSUE TITLE
Content > Wissen > Erste Schritte

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#48]
Text noch erweitern, vielleicht mit Unterpunkten (Kategorien, Komponenten, Module, Plugins) anreichern.
Vorschlag: Statt Zürich ein Beispiel mit Berlin, Köln oder München?

**Comment by coolcat-creations** [comment]
Zurückgestellt für spätere Version

**Comment by zero-24** [comment]
Ist umgesetzt kann also geschlossen werden?
![image](https://cloud.githubusercontent.com/assets/2596554/18798823/9c3636ae-81d4-11e6-9c05-1657526b2bcf.png)

Zürich habe ich nicht mehr gefunden --> obsolet oder übsehen?

**Comment by widmann-it** [comment]
geschlossen ;-)
