### ISSUE TITLE
Dev > Slideshow > Fullwidth (GalaxyTab)

### ISSUE THREAD

**Issue by webnet-assmann** [JandBeyond/joomlade#50]
![screenshot-galaxy](https://cloud.githubusercontent.com/assets/13391559/9405521/a494e2b2-47f8-11e5-8121-bcbd1f771af4.jpg)

**Comment by ufuk-avcu** [comment]
Ich habe hier ein GalaxyTab4 mit 7 Zoll und da sieht es nicht so aus. Kann das noch jemand überprüfen?

**Comment by SniperSister** [comment]
Scheinbar auf aktuellen Androids nicht nachvollziehbar - lasst mal schauen ob das auch von anderen gemeldet wird, dann können wir das nochmal anschauen
