### ISSUE TITLE
Content > Joomla > Links

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#53]
http://relaunch.joomla.de/index.php/joomla/links

Ideen wie man das sinnig darstellt oder wollen wir das für die V 2.0 aufschieben?

**Comment by webnet-assmann** [comment]
Vielleicht wie auf der aktuellen Seite joomla.de als zwei Spalten. Man müsste die Links auch mal aktualisieren. www.joomla-downloads.de gibt es z.b. nicht mehr. Alle Links mal prüfen.

**Comment by ufuk-avcu** [comment]
Wenn ich darf würde ich es eben so machen: https://www.facebook.com/notes/joomla-deutschland/linksammlung-joomla/381951581978654 . Ohne Akkordion...

**Comment by coolcat-creations** [comment]
Aufbau in dieser Art wäre schöner/ansprechender ![links](https://cloud.githubusercontent.com/assets/828371/9836878/d1dd0a6c-5a2a-11e5-9b82-e2859848955e.jpg)

**Comment by d4shoerncheN** [comment]
@ufuk-avcu, wollen wir uns zusammen darum kümmern?

**Comment by degobbis** [comment]
@ufuk-avcu @d4shoerncheN was schwebt euch denn da vor, für die Umsetzung?
Ich dachte da z.b. an eine Anpassung der Weblinks-Komponente oder ein einfaches Content-Plugin.

**Comment by d4shoerncheN** [comment]
@degobbis, wenn wir uns an die Vorlage von @designbengel halten, sollte die Weblinks-Komponente ausreichend sein. Mehr als Titel, Beschreibung und erstes Bild benötigen wir bei der Ausgabe ja nicht. Was meint ihr?

**Comment by coolcat-creations** [comment]
Von mir aus gerne!
Danke!

**Comment by degobbis** [comment]
J! Oder hat's auf Github https://github.com/JOverItsNotOver geschafft, dann können wir den override gleich zuspielen :-)

**Comment by d4shoerncheN** [comment]
@degobbis gibt uns nur noch ein paar Tage Zeit, wir müssen erst die genaue Struktur überlegen, bevor wir Github komplett nutzen.

**Comment by degobbis** [comment]
schon ein gutes Stück weiter :-)
Eine Auflistung mit Weblinks-Kategorie als Überschrift und den Links als Liste geht schon mal.
Jetzt nur noch die Bilder und Beschreibungen reinzaubern.

**Comment by degobbis** [comment]
hier kann man schon was sehen http://relaunch.joomla.de/joomla/links-2

**Comment by SniperSister** [comment]
Aktueller Stand ist hier zu sehen, jetzt muss nurnoch der aktuelle Content in die Weblinks-Komponente überführt werden: https://www.joomla.de/weblinkstest

**Comment by zero-24** [comment]
Ist es gewollt hier das gesamte portfolio an joomla.org Webseiten zu verlinken? Also fast alles was es hier gibt: https://github.com/joomla/joomla-websites/blob/master/README.md oder erstmal das was in der FB Gruppe steht?

**Comment by zero-24** [comment]
Ich hab mal ein paar Beispiele hinzugefügt:
![image](https://cloud.githubusercontent.com/assets/2596554/18799490/1fb1d9f4-81d8-11e6-8566-749d0a3fc496.png)

Dadurch würden wir keine 100m lange Seite produzieren und hätten die Sachen thematisch zusammen?

Was dann noch fehlt sind irgendwelche Schönen Icons / Bilder für `Social Media` oder `Entwicklung etc` :smile: Was haltet Ihr davon?

**Comment by widmann-it** [comment]
Ist in Ordnung so ;-)

**Comment by zero-24** [comment]
Hast du schöne Bildchen oder eine Quele wo ich die am besten herbekomme?

**Comment by coolcat-creations** [comment]
Zieht sich das nicht automatisch die Screenshots?

**Comment by zero-24** [comment]
Nicht das ich wüsste. Aber wenn du mir sagst wie das geht :smile: 

Ich wollte auch eingentlich "nur" Bilder für die einzelnen Bereiche also z.B. Social Media, Entwicklung, Forum, JUGs, Sicherheit

Und dann alle Links zu dem Thema aus Facebook da eintragen: https://www.facebook.com/notes/joomla-deutschland/linksammlung-joomla/381951581978654

**Comment by coolcat-creations** [comment]
Der override kommt von @degobbis  :)

**Comment by zero-24** [comment]
Ja. Aber in dem Override wird kein Screenshot von der verlinkten Seite gehohlt das sind Bilder die händisch eingepflegt wurden :)

**Comment by widmann-it** [comment]
Wie weit seit Ihr ;-)

**Comment by tecpromotion** [comment]
closed
