### ISSUE TITLE
Template -> Überall -> Horizonateler Scrollbalken wenn css Klasse fullwidth verwendet wird.

### ISSUE THREAD

**Issue by ufuk-avcu** [JandBeyond/joomlade#54]
Dies muss in queries.less:54 angepasst werden: 
.fullwidth {
    width: 100vw;
    margin-left: calc((100vw - 1170px + 30px) / 2 \* -1);
}
Vermutlich liegt das Problem bei 100vw, da der Scrollbalken wohl nicht mit kalkuliert wird.

Getestet in Firefox und Chrome

**Comment by SniperSister** [comment]
Wo kann ich das reproduzieren? Hatte eignentlich genau den Fehler vor ein paar Minuten gefixt

**Comment by ufuk-avcu** [comment]
Z.B. http://relaunch.joomla.de/index.php/news  mit Firefox bei einem maximerten Fenster bei einer Monitorauflösung von 1920x1080. Unterhalb von einem VW von ca. 1200px verschwinden die Balken auch bei mir. Aber dafür ist dann Links und rechts ein Padding bei den News. Das kann aber auch absicht sein...

**Comment by SniperSister** [comment]
Fixed
