### ISSUE TITLE
Content > Neuerungen verlinken

### ISSUE THREAD

**Issue by SniperSister** [JandBeyond/joomlade#56]
Die Neuerungen von Joomla 3 im entsprechenden Modul auf der Startseite müssen noch korrekt verlinkt werden

**Comment by coolcat-creations** [comment]
Und der Bratwurstbräter Easteregg muss noch raus ;)

**Comment by SniperSister** [comment]
Denke mal dafür muss erst die Features Seite rein, oder?

**Comment by coolcat-creations** [comment]
oh ja :)

**Comment by SniperSister** [comment]
Erledigt
