### ISSUE TITLE
SEO > Erstcheck

### ISSUE THREAD

**Issue by SniperSister** [JandBeyond/joomlade#59]
@conwebia kannst du mal einen groben Erstcheck der Seite machen, damit wir beim launch keinen Bullshit produzieren?

**Comment by coolcat-creations** [comment]
• Mehrere H1 auf http://relaunch.joomla.de/index.php/haftungsausschluss entfernen
• Keine H1 haben: 
http://relaunch.joomla.de/index.php/news 
http://relaunch.joomla.de/index.php/news/28-joomla/30-joomla-3-4-4-als-hotfix-verfuegbar
http://relaunch.joomla.de/index.php/news/29-community/60-10-jahre-joomla-c-t-heft-20-2015  
http://relaunch.joomla.de/index.php/news/28-joomla/59-joomla-3-4-3-als-hotfix-verfuegbar 
http://relaunch.joomla.de/index.php/news/28-joomla/31-joomla-3-4-2-neue-version-erschienen 
http://relaunch.joomla.de/index.php/news/29-community/35-ein-strukturvorschlag-fuer-das-joomla-projekt 
http://relaunch.joomla.de/index.php/news/30-events/37-pizza-bugs-and-fun-de-erfolgreiche-erstauflage 
http://relaunch.joomla.de/index.php/news/28-joomla/36-erstes-bugfix-release-fuer-joomla-3-4 externer 
http://relaunch.joomla.de/index.php/news/31-wissen/38-das-joomla-certification-project-neustart externer 
http://relaunch.joomla.de/index.php/news/29-community/39-joomla-de-supportforum-gestartet externer 
http://relaunch.joomla.de/index.php/17-community/33-strukturaenderung-fuer-die-joomla-arbeitsgruppen 
http://relaunch.joomla.de/index.php/news/30-events/9-joomla-besser-machen-ein-mitmach-tag externer 
http://relaunch.joomla.de/index.php/news?limitstart externer Link
http://relaunch.joomla.de/index.php/news/28-joomla/10-joomla-3-4-als-stabile-version-erschienen 
http://relaunch.joomla.de/index.php/news/28-joomla/41-support-ende-fuer-joomla-2-5 externer Link

**Comment by coolcat-creations** [comment]
URL rewrite einschalten (index.php entfernen)

**Comment by coolcat-creations** [comment]
Newsbeiträge haben eine zu lange URL

**Comment by SniperSister** [comment]
SEO URls sind an

**Comment by coolcat-creations** [comment]
Duplicate Title
http://relaunch.joomla.de/index.php/news externer Link
http://relaunch.joomla.de/index.php/news?limitstart externer Link
http://relaunch.joomla.de/index.php/community externer Link
http://relaunch.joomla.de/index.php/component/tags/tag/43-community externer Link
http://relaunch.joomla.de/index.php/community/jugs externer Link
http://relaunch.joomla.de/index.php/events/jugs externer Link
http://relaunch.joomla.de/index.php/component/tags/tag/41-usergroups externer Link

**Comment by coolcat-creations** [comment]
Duplicate Content
http://relaunch.joomla.de/index.php/news externer Link
http://relaunch.joomla.de/index.php/news?limitstart externer Link
http://relaunch.joomla.de externer Link
http://relaunch.joomla.de/index.php externer Link
http://relaunch.joomla.de/index.php/17-community/33-strukturaenderung-fuer-die-joomla-arbeitsgruppen externer Link

**Comment by coolcat-creations** [comment]
- Canonical Links sind nicht gesetzt
- Eigenständige Metadescriptions je Beitrag fehlen
- Kein Meta Robots Tag gefunden
- Es werden inline-styles verwender
- Viele Links ohne Titel Attribut
- Browsertitle ist zu kurz

**Comment by coolcat-creations** [comment]
Quelle: Xovi (Ich kann nix dafür) :-)

**Comment by SniperSister** [comment]
Was ist hiervon noch offen?

**Comment by coolcat-creations** [comment]
- Joomla setzt gar kein Meta Robots Tag wenn die Seite  "index, follow" ist...
- Inline-Styles werden verwendet (Bild folgt)
- Teilweise noch zu große Bilder (Bild folgt)
- noch viele zu kurze Browsertitle ~ hm vielleicht ist das alles eher Feintuning für Meilenstein 2.0

**Comment by coolcat-creations** [comment]
![bildschirmfoto 2015-09-16 um 17 37 34](https://cloud.githubusercontent.com/assets/828371/9909744/cef313de-5c99-11e5-93f6-d0da1ba97251.png)
![bildschirmfoto 2015-09-16 um 17 36 08](https://cloud.githubusercontent.com/assets/828371/9909746/cef88666-5c99-11e5-92f0-d72959ca9b5b.png)
![bildschirmfoto 2015-09-16 um 17 35 54](https://cloud.githubusercontent.com/assets/828371/9909743/cef1d974-5c99-11e5-97a3-7aeb8209d0f1.png)
![bildschirmfoto 2015-09-16 um 17 35 44](https://cloud.githubusercontent.com/assets/828371/9909745/cef4389a-5c99-11e5-9baa-e9b98e8bb566.png)

**Comment by SniperSister** [comment]
Das erste ist ein "won't fix", der Rest auf jeden Fall Detailarbeit - ich Milestone das mal...

**Comment by widmann-it** [comment]
Wie sieht es hier aus ;-)

**Comment by widmann-it** [comment]
Sachstand :-)  Sollten den Punkt auch mal Abarbeiten :-)

**Comment by zero-24** [comment]
Wo bekommt man einen Screenshot wie von @coolcat-creations her? ggf. könnte man dazu mal eine neue Auswertung machen und die Sachen fixen?

**Comment by drmenzelit** [comment]
Elisa erwähnt oben Xovi: https://www.xovi.de/
Von Stefanie kenne ich ScreamingFrog... bin aber keine SEO Spezialistin

**Comment by zero-24** [comment]
Danke hab ich wohl überlesen. Ich sehe mir das mal ie Tage an das Tool.

**Comment by tecpromotion** [comment]
closed
