### ISSUE TITLE
Design&Dev > Forum > Anpassung des Forumdesigns

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#6]
Das Forum sollte zumindest ein bisschen an die neue Joomla.de Seite angepasst werden, gerne übernehme ich das direkt. Brauche nur die Zugangsdaten...

**Comment by coolcat-creations** [comment]
@SniperSister Kannst du mir die Zugangsdaten geben, ich schaue mir an wie ich das anpassen kann :-)

**Comment by SniperSister** [comment]
Lass das mal bitte zurückstellen, muss das erstmal mit dem Forenteam abklären :)

**Comment by SniperSister** [comment]
Das ist auch erledigt
