### ISSUE TITLE
Design&Dev > Styling top-b module > Fehlerhafte darstellung zwischen 991px und 1200px

### ISSUE THREAD

**Issue by dneukirchen** [JandBeyond/joomlade#60]
![bildschirmfoto 2015-09-15 um 11 47 11](https://cloud.githubusercontent.com/assets/1134007/9873419/ec67bb54-5b9f-11e5-90bc-e8cbed7f56be.png)

**Comment by SniperSister** [comment]
Fixed by f311a4e
