### ISSUE TITLE
Startseite > Aktuelles Slider > Improvements

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#64]
Wenn Überschrift und Einleitungstext eine einheitliche Höhe bekommen, dann springen die Tags unten nicht so rum... ![aktuelles](https://cloud.githubusercontent.com/assets/828371/9880623/a8e0ac24-5bcc-11e5-9f1a-4d30196191c6.jpg)

**Comment by ufuk-avcu** [comment]
Leider haben die Beiträge unterschiedlich lange Titel. Da gäbe es mehrere Möglichkeiten. Wir schneiden die Titel nach einer bestimmten länge ab und ersetzen es durch drei Punkte. Oder wir machen es mit purem CSS wie uikit: http://getuikit.com/docs/text.html dort bei .uk-text-truncate. Oder wir versuchen wirklich kurze Titel zu fabrizieren, was aber schwierig sein wird. Wir könnten auch dem div Container, feste höhen zuweisen, wie es Elisa sagt. Habt Ihr noch mehr Ideen?

**Comment by widmann-it** [comment]
Ich würde die Überschrift auf 2 Zeilen, Den Text auf max 5 Zeilen und die Tag auf max. 2 Zeilen begrenzen

**Comment by widmann-it** [comment]
Frage !
Sachstand :-)

**Comment by tecpromotion** [comment]
closed
