### ISSUE TITLE
Events > Kalender

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#65]
Heute mit @webnet-assmann festgestellt: Hier wäre die Kalenderblattansicht (alle Termine) schön.
(Meilenstein 2.0)

**Comment by SniperSister** [comment]
Im Menü? Oder das Ding rechts im Menü?

**Comment by coolcat-creations** [comment]
Ehm ich sollte ja einen Link posten: http://relaunch.joomla.de/events
Im mainbody_bottom

**Comment by SniperSister** [comment]
ich bezweifel nach wie vor dass ein Kalenderblatt wirklcih einen Mehrwert hat, da lieber zweispaltige Listen?

**Comment by coolcat-creations** [comment]
irgendwas mit dem man in die "Zukunft" schauen kann? z.B. wann ist JAB16...

**Comment by dneukirchen** [comment]
<img width="1080" alt="bildschirmfoto 2015-09-22 um 20 39 20" src="https://cloud.githubusercontent.com/assets/1134007/10027955/09b81b02-616a-11e5-91ef-419fc1452e64.png">

Hätte das lokal fertig. Benutze das gleiche Modul mit nem anderen Layout, das einfach Jquery Fullcalendar einbaut... Ihr könntet das Modul dann in einem Artikel laden und man hätte mit jetzt knapp 30 Minuten aufwand zumindest die Ansicht des Kalendars (egal ob als Beitrag oder als Modul).

**Comment by coolcat-creations** [comment]
Toll!!! In die mainbody_bottom am besten unter Events
DankeDankeDanke!!!

**Comment by dneukirchen** [comment]
//TODO: Fullcalendar settings als modulparameter

**Comment by dneukirchen** [comment]
// TODO Event & Link Styling

http://relaunch.joomla.de/events

**Comment by d4shoerncheN** [comment]
Ich hab's ein wenig farblich angepasst. Wenn's so ausreicht, stell ich den Code zur Verfügung.

![joomla-de-eventkalender](https://cloud.githubusercontent.com/assets/12725917/10038753/4cf1865a-61ca-11e5-8b78-e86a74211477.jpg)

**Comment by dneukirchen** [comment]
Top, Danke!
