### ISSUE TITLE
Startseite Slideshow > H1 Stil anpassen

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#67]
Ich hab die Überschrift im ersten Slide zu einer h1 gemacht - natürlich ist der Stil jetzt  (bisschen) anders als bei den anderen - kann das jemand korrigieren?

**Comment by SniperSister** [comment]
Ist das eine inhaltlich sinnvolle H1?

**Comment by coolcat-creations** [comment]
naja ... so lala ;-) Können ja gerne noch drüber nachdenken... Aber eine H1 sollte irgendwo hin.

**Comment by SniperSister** [comment]
Dann lass es erstmal so

**Comment by coolcat-creations** [comment]
In der mobilen Ansicht zerstört es leider die Ansicht im ersten Slide

**Comment by SniperSister** [comment]
Fixed
