### ISSUE TITLE
SEO &Styling > Tagsübersicht 

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#68]
Kann man solche Seiten deaktivieren oder anders stylen? 
http://relaunch.joomla.de/component/tags/tag/43-community

**Comment by SniperSister** [comment]
Deaktivieren nein, Stylen ja

**Comment by webgras** [comment]
aber Ihr könntet den Link bei den Tags rausnehmen, dann sind die Artikel getaggt, aber kommt auf die ungestylten Ansichten nicht hin.

**Comment by webgras** [comment]
Also ich meine auf der Seite http://relaunch.joomla.de/news sind die Tags verlinkt, ohne Links sieht es immer noch gut aus :)

**Comment by SniperSister** [comment]
Fixed!
