### ISSUE TITLE
SEO > Robots.txt anpassen

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#69]
?limitstart und tagansicht (/component/tags/tag/...) auf nofollow noindex

**Comment by SniperSister** [comment]
fixed

**Comment by coolcat-creations** [comment]
Disallow: /components/tags/tag/
Disallow: /news?limitstart

muss glaub ich heißen:
Disallow: /component/tags/tag/*
Disallow: /news?limitstart

Danke!

**Comment by coolcat-creations** [comment]
Die Css, JS und Index Dateien müssen glaub ich seit neuestem auch auf index stehen, damit Google die mobile Ansicht beurteilen kann, oder warum auch immer (Da ging doch mal so ein Massen-Alert raus)

Bei den meisten Seiten wird von Xovie angekreidet dass gar kein Meta Robots Tag gefunden wird. Das ist in Joomla auch anscheinend so beabsichtigt, verstehe ich aber nicht. 

Index, Follow   > No robots meta tag is added.

No index, follow    > meta name="robots" content="noindex, follow" 

Index, No follow    > meta name="robots" content="index, nofollow"

No index, no follow > meta name="robots" content="noindex, nofollow"

**Comment by SniperSister** [comment]
@designbengel CSS, Js und Co waren da schon nicht mehr drin, das ist also erledigt.

Was die Index, Follow-Angabe angeht: Xovi soll mal die Standards lesen -.-\* index, follow ist das Standardverhalten, den Tag brauch man nur wenn man explizit was anderes will

Was den Wildcard bei den Tags angeht: ist in der robots.txt nicht nötig, da gilt das rekursiv.

Daher _closed_
