### ISSUE TITLE
Feinarbeit > Inline-Styles entfernen

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#70]
(Meilenstein 2.0)
Auf fast allen Seiten verstecken sich Inline-Styles... Auflistung wäre hier zu lang...
Beispiel: http://relaunch.joomla.de/news/31-wissen/38-joomla-zertifizierung .....  p style="align:justify;"

**Comment by ufuk-avcu** [comment]
Könnte bitte jemand diese CSS Anweisung einfügen. Danach würde ich alle News durchgehen und die inline Styles entfernen.
`.news_beitrag o{text-align:justify;}`
und vorsorglich noch eine Klasse, damit man in Zukunft auf Inline-Style verzichten kann.
`.text-align-justify{text-align:justify;}`

**Comment by widmann-it** [comment]
wer kann das Übernehmen :-)

**Comment by zero-24** [comment]
Obiges Beispiel hat sich erledigt auf der seite sind keine Inline-Styles mehr im Beitrag. Daher mache ich das mal bis auf weiteres zu. Wenn jemand noch inline styles findet. Bitte einen neuen Issue auf machen 👍
