### ISSUE TITLE
Feinarbeit > Dateigrößen checken

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#71]
(Meilenstein 2.0) 
http://relaunch.joomla.de/images/Beitragsbilder/forum.jpg
http://relaunch.joomla.de/templates/joomlade/js/joomlade.js 
http://relaunch.joomla.de/images/slideshow/startseite/joomla_events.jpg 
http://relaunch.joomla.de/templates/joomlade/css/joomlade.css
http://relaunch.joomla.de/images/Beitragsbilder/jandbeyond_bcn.jpg
http://relaunch.joomla.de/images/Beitragsbilder/joomla34graphic.png
http://relaunch.joomla.de/images/Beitragsbilder/25-farewell.png 
http://relaunch.joomla.de/images/aktuelles/joomladay_de_big.png 
http://relaunch.joomla.de/images/downloads/joomla-broeschuere-2015.pdf
http://relaunch.joomla.de/images/Beitragsbilder/pbf.jpg 
http://relaunch.joomla.de/images/Beitragsbilder/JCP.jpg

**Comment by SniperSister** [comment]
Hab imageoptim drüber laufen lassen, im Schnitt ca. 20% verkleinert
