### ISSUE TITLE
Canonical Links Fix > Darf ich das hier installieren?

### ISSUE THREAD

**Issue by coolcat-creations** [JandBeyond/joomlade#73]
http://styleware.eu/store/item/26-styleware-content-canonical-plugin

**Comment by SniperSister** [comment]
Bitte bitte bitte nicht :(

**Comment by coolcat-creations** [comment]
Ok, eine andere Idee die Canonicals einzustellen ? :) wegen SEO und so...

**Comment by SniperSister** [comment]
Verstehe das Problem noch nicht. Joomla generiert die doch sowieso wo nötig?

**Comment by coolcat-creations** [comment]
Ja aber falsch....
Siehe z.B.: http://relaunch.joomla.de/news/30-joomla/joomla-3-4-4-als-hotfix-verfuegbar

**Comment by SniperSister** [comment]
Hast du ne Quelle für den Link? Wo soll das eingetragen sein?

**Comment by coolcat-creations** [comment]
Ok, den habe ich einfach so eingegeben aber dann müsste doch eine 404 kommen statt einer völlig falschen Seite, oder nicht?

**Comment by SniperSister** [comment]
Willkommen bei Joomla. Das Routing-System ist an der Stelle kaputt, hoffentlich bringt 3.5 Besserung. Wäre für mich ein Fall von "won't fix"

**Comment by coolcat-creations** [comment]
Na gut... ;)
