### ISSUE TITLE
Startseite > Aktuelles > Tags

### ISSUE THREAD

**Issue by webnet-assmann** [JandBeyond/joomlade#74]
Sieht bei mir so aus:
![screen](https://cloud.githubusercontent.com/assets/13391559/9899069/a20b38e8-5c57-11e5-9717-def29beca2da.jpg)

**Comment by SniperSister** [comment]
Welchen Browser hast du da?

**Comment by webnet-assmann** [comment]
Windows Firefox

**Comment by SniperSister** [comment]
Gefixt von ca23765a
