### ISSUE TITLE
Typo Projektstruktur

### ISSUE THREAD

**Issue by FrankM64** [JandBeyond/joomlade#77]
Link: http://www.joomla.de/joomla/projektstruktur

"Das Urheberrecht **and** der Joomla!-Software"

**Comment by SniperSister** [comment]
Fixed! Danke :)

**Comment by FrankM64** [comment]
Du sollst doch nicht alles gleichzeitig machen ;) Jetzt steht da:

"Das Urheberrecht und der Joomla!-Software und dessen Standardvorlagen liegt bei Open Source Matters, Inc."

Ich denke es soll so aussehen:
"Das Urheberrecht **an** der Joomla!-Software und dessen Standardvorlagen liegt bei Open Source Matters, Inc."

**Comment by SniperSister** [comment]
_Kopf auf Tischplatte_ ja, jetzt wo du's sagst.... erledigt :)

**Comment by FrankM64** [comment]
Jetzt ist schön :)
