### ISSUE TITLE
JoomlaDay DE durch JoomlaDay AT ersetzen

### ISSUE THREAD

**Issue by SniperSister** [JandBeyond/joomlade#78]
Wir brauchen da nur einen netten Banner von @seagul30

**Comment by webgras** [comment]
hier gibt es ein paar Formate: http://joomla-day.at/banner
Falls Ihr was anderes braucht, bitte melden.

**Comment by webgras** [comment]
oh, quadratisch. ich bastle was.

**Comment by webgras** [comment]
![jd15at-banner](https://cloud.githubusercontent.com/assets/10774704/9987306/1b51d12e-6047-11e5-9c60-ad5479345095.jpg)

**Comment by webgras** [comment]
Die Überschrift sollte dann auch sein:
Die nächste **deutschsprachige** Veranstaltung

**Comment by SniperSister** [comment]
Fixed! :)
