### ISSUE TITLE
Schreibfehler auf Startseite

### ISSUE THREAD

**Issue by d4shoerncheN** [JandBeyond/joomlade#81]
Vier Module, alle Überschriften groß geschrieben außer „Wissen“.

Darunter „Vollversion Runterladen“, „runterladen“ klein schreiben.

Bei Punkt „Community“ unter „Usergroups“ würde ich „Deiner“ klein schreiben, da es in den anderen Texten auch immer klein geschrieben wurde.

**Comment by webnet-assmann** [comment]
Ich wäre dafür, Du und Dein groß zu schreiben. Würde auch nochmal den Text dafür durchgehen

**Comment by coolcat-creations** [comment]
Nach Rechtschreibreform 2006 muss das aber klein geschrieben werden :-)

**Comment by webnet-assmann** [comment]
Blöde Rechtschreibreform - aber gut, dann alles klein.

**Comment by webnet-assmann** [comment]
Ist sowieso an manchen Stellen noch mit Sie.
