### ISSUE TITLE
SEO > Umleitung anlegen

### ISSUE THREAD

**Issue by germanis** [JandBeyond/joomlade#82]
Ich würde die recht prominent platzierte URL redirekten:
http://www.joomla.de/joomla-entdecken/framework

BTW, Ihr könnte mich gerne mit reinnehmen, dann kümmere ich mich um solchen Kram.
Ist die Seite schon mit Webmastertools verdrahtet?
Wenn ja, könnt ihr mich mit rein nehmen > germanis.hartenstein@gmail.com

**Comment by SniperSister** [comment]
Erledigt
