### ISSUE TITLE
Kalender -> Events -> JUG Frankfurt

### ISSUE THREAD

**Issue by drmenzelit** [JandBeyond/joomlade#83]
Termin ist nicht im Kalender.

Wenn ich Zugang bekomme, kann ich es selber eintragen :-)

**Comment by christianhent** [comment]
@drmenzelit schick mir bitte via glip mal deine addresse damit ich dich in den google calender als editor adden kann.

**Comment by SniperSister** [comment]
Ist inzwischen wohl erledigt :)
