### ISSUE TITLE
Community -> JUGS

### ISSUE THREAD

**Issue by drmenzelit** [JandBeyond/joomlade#85]
Es wäre besser, wenn die Links zu den JUGS sich in einem neuen Fenster/Tab öffnen würden

**Comment by SniperSister** [comment]
Stimmt, dafür muss nur jemand vorher das weblinks Modul gegenchecken. Stelle ich das auf target Blank werden die Links doppelt angezeigt?!

**Comment by drmenzelit** [comment]
Ich habe keinen Zugang zum Backend :-(

**Comment by SniperSister** [comment]
Du hast nen Account der auch aktiv ist

**Comment by drmenzelit** [comment]
htaccess davor, die Daten habe ich nicht

**Comment by SniperSister** [comment]
Die bekommst du im Glip Chat

**Comment by drmenzelit** [comment]
Also, wenn man im Modul target blank einstellt, erzeugt es 2 links: 1 mit class="visible-phone" und 1 mit class="hidden-phone". Und weil die wahrscheinlich im CSS nicht definiert sind, werden beide angezeigt

**Comment by SniperSister** [comment]
WTF wer hat denn diese gequirlte kacke zusammengebaut. Denke da machen wir nen Override für...

**Comment by d4shoerncheN** [comment]
Dann bitte als Alternatives Layout, wir brauchen die Komponente auch noch :P

**Comment by drmenzelit** [comment]
Ich habe die Änderungen im Override gemacht (Klassen hidden-xs und visible-xs ergänzt), aber ich kann nicht pushen

**Comment by SniperSister** [comment]
Öhm. Im Grunde genommen macht die Dopplung an sich überhaupt keinen Sinn, ich würde das durch nen stinknormalen Link ersetzen.

Was heißt du kannst das nicht pushen?

**Comment by SniperSister** [comment]
Erledigt!
