### ISSUE TITLE
Apple Touch Icon links should be updated

### ISSUE THREAD

**Issue by nternetinspired** [JandBeyond/joomlade#86]
The way iOS devices request these images changed since iOS8 (For full details see:https://github.com/h5bp/html5-boilerplate/commit/345925f04384b59929d8d39ba428cef548921408)

Personally, I now go with just a single image `apple-touch-icon.png` at 180x180px as that suits even retina devices and isn't really a burden for smaller devices, they can make use of it as well.

Incidentally, you can add a rel link the _Joomla way_ in your template logic using:

```
// Point all iOS devices to the Apple Touch Icon (180x180px)
$doc->addHeadLink($tpath.'/images/apple-touch-icon.png', 'apple-touch-icon');
```

Kind regards,

Seth

**Comment by SniperSister** [comment]
Hi Seth,

sorry that it took so long to get this fixed, after the relaunch everybody was pretty busy earning some money ;) Thanks a lot for your patience and help! :)

Cheers,
David

**Comment by nternetinspired** [comment]
No worries David, it was a proposed enhancement so not something that needed 'fixing' immediately.

Glad to hear you are all busy earning now, I'm looking for some more of that myself currently! ;)

Cheers :beers:
