### ISSUE TITLE
Imperative auf Startseite

### ISSUE THREAD

**Issue by floriandotpy** [JandBeyond/joomlade#89]
Der Content selbst ist ja nicht im Repository, daher meine Korrektur hier als Issue. Auf der Startseite sollten folgende Imperative korrigiert werden:

Aktuell: "Sei ein Teil von Joomla!, **helfe** anderen und profitiere selbst."
Besser: "Sei ein Teil von Joomla!, **hilf** anderen und profitiere selbst."

Aktuell: "**TREFFE** DICH MIT ANDEREN USERN AUS DEINER STADT"
Besser: "**TRIFF** DICH MIT ANDEREN USERN AUS DEINER STADT"

**Comment by dneukirchen** [comment]
Ist geändert. Vielen Dank für den Hinweis!
