### ISSUE TITLE
Joomla 3.4.4

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#94]
Hi,

auch wenn es etwas kleinlich ist ;) Joomla 3.4.4 ist kein Hotfix release :smile: Es war ein Sicherheitsrelease oder Wartungsrelease aber kein Hotfix :smiley: 

http://www.joomla.de/news/28-joomla/30-joomla-3-4-4-als-hotfix-verfuegbar

**Comment by SniperSister** [comment]
Fixed :)

**Comment by zero-24** [comment]
:+1:
