### ISSUE TITLE
[joomlade] Button "so gehts" fürs bugtesting

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#95]
Hallo,

aktuell linkt ihr auf: https://docs.joomla.org/Filing_bugs_and_issues dies behandelt aber eher das allgemeine Bug melden etc. fürs testen ist vielleicht das hier besser: https://docs.joomla.org/Testing_Joomla!_patches

![testing_link](https://cloud.githubusercontent.com/assets/2596554/10188414/67eea7ea-675f-11e5-9d0c-d388d9546eaf.JPG)

:smile:

**Comment by SniperSister** [comment]
Danke für den Tip :) Fixed!
