### ISSUE TITLE
Responsive Submenu - Untermenus sind zT. nicht sichtbar 

### ISSUE THREAD

**Issue by dneukirchen** [JandBeyond/joomlade#98]
Untermenus werden auf kleineren Auflösungen zT außerhalb des viewports dargestellt und sind daher nicht oder nur teilweise sichtbar. 

> Hier sollte es so geämndert werden das de Untermenüs linksbündig aufgehen.

![bildschirmfoto 2015-10-15 um 09 47 56](https://cloud.githubusercontent.com/assets/1134007/10507612/fe35c6fc-7321-11e5-97a1-9d84d3762d05.png)

 Dieses Issue wurde von der JUG Koblenz gefunden.

**Comment by widmann-it** [comment]
Ist Aktuell auch noch so !
