### ISSUE TITLE
4 gebrochene Links ;)

### ISSUE THREAD

**Issue by zero-24** [JandBeyond/joomlade#99]
Hier:
http://www.joomla.de/news/30-events/64-joomla-nochmal-besser-machen-pizza-bugs-and-fun-2-0

JUG Sauerland geht nach http://www.joomla.de/www.jug-sauerland.de sollte nach http://www.jug-sauerland.de gehen

die anderen 3 sind hier: http://www.joomla.de/joomla

IN WELCHEN SPRACHEN IST JOOMLA! VERFÜGBAR? -> mehrsprachiger Inhalte -> geht nach http://www.joomla.de/joomla-entdecken/begriffserklaerung#languages --> 404

WIE ZUKUNFTSSICHER IST JOOMLA!? -> Veröffentlichungsstrategie --> geht nach: http://www.joomla.de/joomla-entdecken/releasestrategie -> 404

JOOMLA! IST DIE RICHTIGE LÖSUNG! WIE FANGE ICH AN? -> geht nach: http://www.joomla.de/joomla-entdecken/ressourcen --> 404

**Comment by drmenzelit** [comment]
Der Link zu JUG Sauerland habe ich korrigiert.

"joomla-entdecken" gibt es nicht... Im Beitrag "Joomla! Grundbegriffe" wird "Sprachen" erwähnt, aber ist noch nicht erklärt um es verlinken zu können.
Es gibt ein Releasestrategie Beitrag, soll man mit dem direkt verlinken?
Zu Ressourcen habe ich nichts entdeckt...

**Comment by zero-24** [comment]
ja vielleicht sind das einfach nur alte Links ggf. noch von der alten seite?

**Comment by drmenzelit** [comment]
Weißt jemand warum der Link http://www.joomla.de/wissen#sprachen nicht den Tab Sprachen öffnet?

Soll man Releasestrategie als Unterpunkt von Projektstruktur anlegen?

**Comment by drmenzelit** [comment]
JOOMLA! IST DIE RICHTIGE LÖSUNG! WIE FANGE ICH AN? -> geht nach: http://www.joomla.de/joomla-entdecken/ressourcen --> 404

Habe ich jetzt mit "Links" verlinkt

**Comment by zero-24** [comment]
@drmenzelit oh ist der issue hier alt :)

Der letzte der noch in der Liste steht ist: 

> WIE ZUKUNFTSSICHER IST JOOMLA!? -> Veröffentlichungsstrategie --> geht nach: http://www.joomla.de/joomla-entdecken/releasestrategie -> 404

Was hältst du davon das auf: http://magazine.joomla.org/international-stories-all/articles-in-german-all/der-neue-joomla-release-zyklus zu verlinken?

**Comment by SniperSister** [comment]
Erledigt :)
